### ISSUE TITLE
Missing Android Studio Project Files

### ISSUE THREAD

**Issue by Jonathan727** [opendatakit/opendatakit#1]
The readme for the collect project refers to a .iml file that isn't in the master branch.

**Comment by Jonathan727** [comment]
Looks like `*.iml` files have been ignored since db28500c38ff2b017a4acdec5900fc563407c687

**Comment by jbeorse** [comment]
We decided to stock tracking .iml files and other configuration files. I have removed all references to them in our README files.

If you open the root directory of the project with Android Studio, a new iml file should be created. We are working on providing sample .iml files if you want to replicate our test configuration.

Another note: for many of our projects the master branch has the most recent stable code, which uses Eclipse. The migrations to Android Studio happened in the development branches, which will be merged back when stable.
