### ISSUE TITLE
how to add auto number in ODK build

### ISSUE THREAD

**Issue by mitchellsundt** [opendatakit/opendatakit#1025]
Originally reported on Google Code with ID 1024
```
please is it possible to add auto number in ODK , i want the numbers to be inserted
automatically by ODK 
thanks  
```

Reported by `eabboud86` on 2014-06-25 09:55:27

**Comment by marshallb93** [comment]
Please ask any questions such as this in the [Google group](https://groups.google.com/forum/#!forum/opendatakit).

Thanks,

Dev Team
