### ISSUE TITLE
min() and max() to accept nodeset for all argument 

### ISSUE THREAD

**Issue by mitchellsundt** [opendatakit/opendatakit#1045]
Originally reported on Google Code with ID 1044

```
When working on the ODK spec, I noticed that min() and max() only accept the NodeSetType
for the first argument (or am I misreading?).

Would seems worthwhile (and easy enough) to change this to allow any argument to be
of NodeSetType. This would make it conform to XPath 2.0: http://www.w3.org/TR/xpath-functions/#func-max

Already the case in Enketo.
```

Reported by `martijn@enketo.org` on 2014-08-14 21:36:58

**Comment by yanokwa** [comment]
Fixed at https://opendatakit.github.io/xforms-spec/.

**Comment by lognaturel** [comment]
The request was to match XPath 2.0 signatures which are 
```
fn:max($arg as xs:anyAtomicType*) as xs:anyAtomicType?
fn:max($arg as xs:anyAtomicType*, $collation as xs:string) as xs:anyAtomicType?
```

I think it's ok to close and can be discussed elsewhere if needed but want to make it clear it's not addressed.

**Comment by wbrunette** [comment]
@lognaturel feel free to move the issue to where you think is best. We are trying to clear out this issue queue.
