### ISSUE TITLE
How to change IP Address in ODK Aggregate?

### ISSUE THREAD

**Issue by mitchellsundt** [opendatakit/opendatakit#1087]
Originally reported on Google Code with ID 1086
```
I want to change the IP Address of ODK Aggregate without redeploying.
If the IP Address of my server change, I can access TOMCAT Apache Server but cannot
access ODK AGGREGATE.

Is it possible to change the IP Address in ODK Aggregate.
```

Reported by `suman2045` on 2014-11-19 04:19:00

**Comment by marshallb93** [comment]
Please ask any questions such as this in the [Google group](https://groups.google.com/forum/#!forum/opendatakit).

Thanks,

Dev Team
