### ISSUE TITLE
indexed-repeat function

### ISSUE THREAD

**Issue by mitchellsundt** [opendatakit/opendatakit#1097]
Originally reported on Google Code with ID 1096
```
On my XLSForm I've two fields, namely, "MemberID" and "MemberName" which repeats.

I want to populate the records of "MemberID" and "MemberName" on another non-repeat
form where I can select or choose.

Thank you very much in advance.
```

Reported by `ssonamtshering` on 2014-12-20 19:37:43

**Comment by marshallb93** [comment]
Please ask any questions such as this in the [Google group](https://groups.google.com/forum/#!forum/opendatakit).

Thanks,

Dev Team
