### ISSUE TITLE
Hi dears I can not Access my Aggregate using App engine ??? 

### ISSUE THREAD

**Issue by mitchellsundt** [opendatakit/opendatakit#1100]
Originally reported on Google Code with ID 1099
```
I have problem with Username and Password !
regards 

```

Reported by `akko.architect` on 2015-01-12 07:28:28

**Comment by marshallb93** [comment]
Please use our [Google group](https://groups.google.com/forum/#!forum/opendatakit) for issues such as this.

Thanks,

Dev Team
