### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by mitchellsundt** [opendatakit/opendatakit#1102]
Originally reported on Google Code with ID 1101
```
My problem is that I can't log in into my ODK aggregate page. I'm having the following
message: This server and its data are not secure! Please change the super-user's password!
As far as I remember I didn't set up any user and password. I don't see the permission
sub-tab also.

```

Reported by `gugalde.msalud` on 2015-01-13 17:13:44

**Comment by marshallb93** [comment]
Please ask any questions such as this in the [Google group](https://groups.google.com/forum/#!forum/opendatakit).

Thanks,

Dev Team
