### ISSUE TITLE
How to copy a date value from one field to another

### ISSUE THREAD

**Issue by mitchellsundt** [opendatakit/opendatakit#1103]
Originally reported on Google Code with ID 1102

```
Im able to use previous variables to populate new ones/copy values from one field to
other using XLSForm.
But with one exception I cant copy date values to another date field.

Any help?
```

Reported by `paulphilimone` on 2015-01-28 23:29:15

**Comment by yanokwa** [comment]
I don't think you've ever been able to copy values from one field to another without. I'm closing this issue for that reason.
