### ISSUE TITLE
select_one_external only seems to work for cascading examples

### ISSUE THREAD

**Issue by mitchellsundt** [opendatakit/opendatakit#1132]
Originally reported on Google Code with ID 1131

```
What steps will reproduce the problem?
1. attempt to parse the attached file through xlsform.exe

What is the expected output? What do you see instead?
Valid xml output (optimally with the expected "itemsets.csv" but that's a different
bug)

What version of the product are you using? On what operating system?
1.45 on Windows 7


Please provide any additional information below.

From xlsform.org:

"Enabling external selects is straightforward. - Instead of select_one for the prompt
type, use select_one_external. - Instead of the choices sheet, put external choices
in the external_choices sheet." 

Suggests that for a form with a large number of options, one should be able to use
external choices so they're loaded from itemsets.csv rather than parsed on opening
the .xml file and wedging up memory.

The only examples The Google can find are cascading choices, all about drilling down
through supersets to a small geographic locality from a larger one.  In each example,
the initial choice list is an "example of a standard one" meaning it is listed in the
"choices" tab rather than the "external_choices" tab.  If you have a "select_one_external"
without a choice_filter entry (as you would if it was not part of a cascading list),
conversion fails with a 

[row : {n}] List name not in choices sheet: {name} 

error. 
```

Reported by `dgessel` on 2015-04-19 01:56:38

**Comment by yanokwa** [comment]
We now warn about this in pyxform. https://github.com/XLSForm/pyxform/blob/a0b69a5f754d00150c324904017080f09c7c1927/pyxform/xls2json.py#L831

**Comment by hishamgmail** [comment]
I am trying to upload xls file with cascading select to opendatakit. put there is a Error: [row : 33]List name not in external choices sheet: admin2
the choice_filter has the 
governorate1=${admin1}
district1=${admin2}
sub_district1=${admin3}

so why the opendatakit. give me this error message [row : 33]List name not in external choices sheet: admin2

in kobo it is ok and it open 
but i need to change the form from xls to xml to use google file , so how can I do that in opendatakit.

type	name	Label	choice_filter
begin_group	geo_data	Select Government	
select_one admin1	admin1	Select The Government	
select_one_external admin2	admin2	Select City Or District?	governorate1=${admin1}
select_one_external admin3	admin3	Select Sub-District?	district1=${admin2}
select_one_external admin4	admin4	Select The Village	sub_district1=${admin3}
end_group			

and in external_choices
file name itemsets
list_name	name	label	Governorate1	District1	Sub_district1	Communities1
admin2	1101	Al Qafr	11			
admin3	111023	Al Masil	11	1110		
admin4	11578	ALWASAT 17	1713	171321	

HELP ME PLEASE

**Comment by wbrunette** [comment]
@hishamgmail please ask for help on forum.opendatakit.org or file a issue  on the issue queue for the tool you think is  failing. We are no longer using this issue queue which is why this issue is closed.

**Comment by hishamgmail** [comment]
done
