### ISSUE TITLE
Can not publish to a Google Spreadsheet

### ISSUE THREAD

**Issue by mitchellsundt** [opendatakit/opendatakit#1141]
Originally reported on Google Code with ID 1140

```
What steps will reproduce the problem?
1. On the submissions page - Publish - Google Spreadsheet - Publish
2.
3.

What is the expected output? What do you see instead?
Expect it to publish.  I get an error about the Doclist APi being shutdown.  See attached
screen shot.

What version of the product are you using? On what operating system?
Win 7.  Version 1.4.5 production

Please provide any additional information below.
Google Fusion Tables works but Spreadsheet does not.  Searched and never found this
error listed.
```

Reported by `hfmnw0` on 2015-04-30 15:59:24

<hr>
- _Attachment: Speadsheet Error.PNG<br>![Speadsheet Error.PNG](https://storage.googleapis.com/google-code-attachments/opendatakit/issue-1140/comment-0/Speadsheet Error.PNG)_

**Comment by jbeorse** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jeffisveryhungry@gmail.com
    Domain beorse.net has exceeded the max emails per hour (251/250 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o10.sgmail.github.com ([167.89.101.201]:41326)
	by hp159.hostpapa.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-c877-jeff=beorse.net@sgmail.github.com>)
	id 1dgMC7-000eJR-RS
	for jeff@beorse.net; Fri, 11 Aug 2017 22:30:31 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=cpqN1QrwFc/cPZk8MJbinxpQ6JM=; b=OLwGC5zc4MuzSXm+
	szsRQoAZiHtvjj8pp2fpD1rvgUgpO7eCe9aLiZ+e4RIobu7BL+gXOtQMoa/Y1zC5
	iZKQ5UaaMo+NggomT1dlfr0knqqtG2iRJh5UpnAUuF/S6CDeVSY4B/3gzq8SgExg
	ZuqbXp8PIt7MT9gdccut89uzucE=
Received: by filter0927p1mdw1.sendgrid.net with SMTP id filter0927p1mdw1-11003-598E6820-11
        2017-08-12 02:29:52.164865304 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0037p1mdw1.sendgrid.net (SG) with ESMTP id joQUhQ0TQFqE4HRwcxtx5g
	for <Jeff@Beorse.net>; Sat, 12 Aug 2017 02:29:52.132 +0000 (UTC)
Date: Sat, 12 Aug 2017 02:29:52 +0000 (UTC)
