### ISSUE TITLE
publishers are not usable with doubly-nested repeat groups

### ISSUE THREAD

**Issue by mitchellsundt** [opendatakit/opendatakit#1142]
Originally reported on Google Code with ID 1141

```
When repeat groups are published to fusion tables and/or spreadsheets,
they include a parent-uid field but are missing their self-uid field.

That is needed in order to join nested repeat groups back to their enclosing repeat
group, and from there, up the chain, to the top-level instance id.

Briefcase exports do work, because those export this info as KEY and PARENT_KEY,
allowing these to be joined back together.


```

Reported by `mitchellsundt` on 2015-04-30 18:03:24

**Comment by jbeorse** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jeffisveryhungry@gmail.com
    Domain beorse.net has exceeded the max emails per hour (255/250 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o7.sgmail.github.com ([167.89.101.198]:45641)
	by hp159.hostpapa.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-c877-jeff=beorse.net@sgmail.github.com>)
	id 1dgMCB-000eKA-1l
	for jeff@beorse.net; Fri, 11 Aug 2017 22:30:35 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=CCBJKD/ZhRxXeux4Wv6DbcxpJHQ=; b=ImLCYJBCm8O3gFyu
	DwH0mJtnkUgE8vZTofFdCZ5VGPUzehpb37VZYI8QUkdGUbZl36ib4LCVbmO3/oEz
	kiMugIXUhQ+JaRJenjWKywaknvZUVMLteTtgbpEcbpW58KB/nIUZDiVfPiA7ZT4n
	lR1d0on4oMU3dz0cKie6UeE7Pbo=
Received: by filter0635p1mdw1.sendgrid.net with SMTP id filter0635p1mdw1-5634-598E6821-40
        2017-08-12 02:29:53.745439196 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0037p1mdw1.sendgrid.net (SG) with ESMTP id qp-p4FzGR3WUFqtZW_TfHg
	for <Jeff@Beorse.net>; Sat, 12 Aug 2017 02:29:53.746 +0000 (UTC)
Date: Sat, 12 Aug 2017 02:29:53 +0000 (UTC)
