### ISSUE TITLE
Ajax request - survey 2.0 - choice_filter

### ISSUE THREAD

**Issue by mitchellsundt** [opendatakit/opendatakit#1144]
Originally reported on Google Code with ID 1143
```

Hy

Is there any way to use the "choice_filter" column from survey to filter a list of
choices rendered by an ajax call in the queries worksheet?

Thank you

```

Reported by `dumitrache.andrei85` on 2015-05-05 09:06:20

**Comment by marshallb93** [comment]
Please use our [Google group](https://groups.google.com/forum/#!forum/opendatakit) for issues such as this.

Thanks,

Dev Team
