### ISSUE TITLE
"ODK Tables Syncronization Functionality" (sic) *Synchronization 

### ISSUE THREAD

**Issue by mitchellsundt** [opendatakit/opendatakit#1149]
Originally reported on Google Code with ID 1148

```
Synchronization is misspelled in /Aggregate.html#admin/preferences///
```

Reported by `dgessel` on 2015-06-06 15:25:38

**Comment by jbeorse** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jeffisveryhungry@gmail.com
    Domain beorse.net has exceeded the max emails per hour (254/250 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:33608 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by hp159.hostpapa.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89)
	(envelope-from <noreply@github.com>)
	id 1dgMCA-000eKQ-MZ
	for Jeff@Beorse.net; Fri, 11 Aug 2017 22:30:34 -0400
Date: Fri, 11 Aug 2017 19:29:55 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1502504995;
	bh=eDA+EqsB2isgdLHzakHG0zXeudhtMGomNEDj2qKtW1U=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=VwV/D+GGf0nT0iTeQYsrSHVFiKOg1EZIv2B8ncpWOvwbxyg2uinfZGKz68A1IszyZ
	 TYZiMUKIyg0tT8eqbnZYItHJZHDtOVFXE+bgyG3fRIWgRtdsUXkIdZuUp+/YBRvIhl
	 f3qJ26WgsJXN6lQl+gK5jTCwF2EelVjpzAtBu/F8=
