### ISSUE TITLE
In filters "Where" clause is diabled

### ISSUE THREAD

**Issue by mitchellsundt** [opendatakit/opendatakit#1150]
Originally reported on Google Code with ID 1149

```
What steps will reproduce the problem?
1. Click on Add Filter


What is the expected output? What do you see instead?
I can mention the where clause for filtering data.
Instead of it where clause is disabled.

What version of the product are you using? On what operating system?
ODK Aggregate 1.4.7 on Windows Server 2008

Please provide any additional information below.

```

Reported by `piyushsh18` on 2015-06-08 05:18:01

<hr>
- _Attachment: Untitled.png<br>![Untitled.png](https://storage.googleapis.com/google-code-attachments/opendatakit/issue-1149/comment-0/Untitled.png)_

**Comment by r2rivera** [comment]
Hi guys,  just want to ask if there are recent developments on this issue? 

Thanks.

raffy

**Comment by saadaan** [comment]
Hi Mitch, 
This 'filter disabled' issue has become project critical for me, and I need to decide whether to downgrade aggregate to some working version OR wait for new aggregate release and upgrade. Is there any chance the new release would be within a week or so, as it is already March end.
Many thanks,

**Comment by mitchellsundt** [comment]
If it is project critical, I would roll back to the earlier working release. The ODK Aggregate release is my focus. However, the set of changes to the development environment (but not the code itself) are very large, and there are many gotchas that require finding and documenting work-arounds.

**Comment by jbeorse** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jeffisveryhungry@gmail.com
    Domain beorse.net has exceeded the max emails per hour (257/250 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:53422)
	by hp159.hostpapa.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-c877-jeff=beorse.net@sgmail.github.com>)
	id 1dgMCD-000eLX-2F
	for jeff@beorse.net; Fri, 11 Aug 2017 22:30:37 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=KkuI9xdShlFfbf/fJRCJx6NK7gw=; b=r/g2xqm927XVXqvL
	6PmEC86srrNlnLm0fEH/0aUO8yjRviyLMCZRXxFSC6M/UfZdrYlBjdwe1CHxGHQ0
	kbAFOJm7lYweuWc/h1RdPyxyE2jbzBaZ0HDZmlFjel6TxNNmnW3MaT+LBaOH5Nwc
	OnVSoRKBqdRUAjRDGH/KCqmrJ6w=
Received: by filter0826p1mdw1.sendgrid.net with SMTP id filter0826p1mdw1-7338-598E6825-1
        2017-08-12 02:29:57.021372709 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0029p1mdw1.sendgrid.net (SG) with ESMTP id FMai1GCtSOOef4bHPDa_sQ
	for <Jeff@Beorse.net>; Sat, 12 Aug 2017 02:29:56.976 +0000 (UTC)
Date: Sat, 12 Aug 2017 02:29:57 +0000 (UTC)
