### ISSUE TITLE
Error while uploading ODK to google.

### ISSUE THREAD

**Issue by mitchellsundt** [opendatakit/opendatakit#1151]
Originally reported on Google Code with ID 1150

```
Whenever I try to upload the script to google the script fails. The main error is "Application
does not exist"
Where as the the application name that I entered is correct.


Attached is the screenshot of the issue.
Thanks.

```

Reported by `arsaljalib` on 2015-06-23 15:44:58

<hr>
- _Attachment: [Untitled.jpg](https://storage.googleapis.com/google-code-attachments/opendatakit/issue-1150/comment-0/Untitled.jpg)_

**Comment by jbeorse** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jeffisveryhungry@gmail.com
    Domain beorse.net has exceeded the max emails per hour (265/250 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:13117)
	by hp159.hostpapa.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-c877-jeff=beorse.net@sgmail.github.com>)
	id 1dgMCK-000eTD-Nj
	for jeff@beorse.net; Fri, 11 Aug 2017 22:30:44 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=yIbb+5uGPoCIuOoWxPAC0OGQp1g=; b=b90+BzHHYPyNo4MV
	I82KzTyFO+/RTlSp3OU7VpUfsXLGSiNYFajVVjMSbCydhpeiChrRzcTW/ymgEt1i
	PNAxmthu0GL6jYMFadKP/RngSTiJHA/uPQ8R4//Rdax3gCms2VzjTfb+mLP9NCRe
	NXToE5AC+terR5LzTJqz+CLEcrI=
Received: by filter0534p1mdw1.sendgrid.net with SMTP id filter0534p1mdw1-2007-598E682C-1D
        2017-08-12 02:30:04.941013015 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0024p1mdw1.sendgrid.net (SG) with ESMTP id OxXx2HRoSEaXnprW1_WJ9Q
	for <Jeff@Beorse.net>; Sat, 12 Aug 2017 02:30:04.907 +0000 (UTC)
Date: Sat, 12 Aug 2017 02:30:05 +0000 (UTC)
