### ISSUE TITLE
Accessing a Survey within a Survey 

### ISSUE THREAD

**Issue by marshallb93** [opendatakit/opendatakit#1156]
**Steps to reproduce:**
- Open Survey with embedded Survey (e.g. Household Survey)
- Navigate to add internal Survey page (e.g. House Member)
- Click to add the Survey (e.g. Add House Member)

**Expected behavior:** Internal Survey is displayed

**Observed behavior:** "The requested form is missing: " (the form is downloaded and can be opened itself itself)

I'm sure this has something to do with the changes in how tables and forms are referenced.

**Comment by jbeorse** [comment]
Fixed or not an issue as of RC2 or earlier
