### ISSUE TITLE
Broken/Unusable Sliders

### ISSUE THREAD

**Issue by marshallb93** [opendatakit/opendatakit#1157]
**Steps to reproduce:**
- Open form with a slider present (e.g. Example Form)
- Slider is practically unusable (selected value not displayed, touch area too small, lacks any graphics) 

**Expected behavior:** Apparently this used to display properly, and was a usable form feature 

**Observed behavior:** It doesn't.

**Comment by jbeorse** [comment]
Fixed or not an issue as of RC2 or earlier
