### ISSUE TITLE
Preview image broken

### ISSUE THREAD

**Issue by marshallb93** [opendatakit/opendatakit#1159]
**Steps to reproduce:**
- Open a Survey with support for taking and adding images
- Navigate to add image
- Take image and return to Survey

**Expected behavior:** A preview of the previously taken image should be displayed in the preview box.

**Observed behavior:** Instead no preview is displayed, only an "image missing" icon.

Additional info: There is also screen flickering on returning to the Survey from the camera app. This may be related.

**Comment by jbeorse** [comment]
Fixed or not an issue as of RC2 or earlier
