### ISSUE TITLE
Long Press does not appear to work on Android 5.x

### ISSUE THREAD

**Issue by marshallb93** [opendatakit/opendatakit#1160]
**Steps to reproduce:**
- Use Android 5.x
- Open Tables
- "Long press" a table in the list of downloaded tables

**Expected behavior:** A menu with further options for the table is meant to appear (delete table, rename, etc.)

**Observed behavior:** Nothing happens

**Comment by jbeorse** [comment]
Fixed or not an issue as of RC2 or earlier
