### ISSUE TITLE
Geoshape and geotrace data types are retrieved with missing data.

### ISSUE THREAD

**Issue by unmultimedio** [opendatakit/opendatakit#1163]
Hello there. I am using GeoODK with an Aggregate server in appspot. We have a no-required question type **geotrace** to fill a perimeter of a land. Sometimes people are uploading the data but this data is coming with missing values.

Do you know if this is an issue of length of the field? or issue of the GeoODK app that's sending the info with some missing characters?

![bug1](https://cloud.githubusercontent.com/assets/4431392/8811144/9042cf88-2fb9-11e5-9669-c641aea8ecca.jpg)

![bug2](https://cloud.githubusercontent.com/assets/4431392/8811100/0e812e68-2fb9-11e5-82d0-15465ce7e7fe.jpg)

Data is always supposed to be an array of coordinates separated by a semicolon, where each coordinate is a 4-value array separated by spaces.

Is this an issue of Aggregate receiving/exporting the data? or an issue of GeoODK sending it?

**Comment by mitchellsundt** [comment]
ODK Aggregate has a default storage length of 255 characters.

It is entirely possible this is an issue if you are trying to capture more
than 8 coordinates per data capture.  i.e., if you assume a worst-case
geopoint of 10-digit decimal numbers, then you would consume 4*10 + 4 == 44
characters per geopoint in a geotrace.  This would limit you to no more
than 5 coordinates per data capture.  If you assume 2 10-digit values and 2
3-character values (0.0), this would give 30 characters per geopoint,
limiting you to no more than 8 coordinates per data capture.

I forget whether the odk:length attribute is recognized on geotrace /
geoshape fields. See
https://opendatakit.org/help/form-design/guidelines/#datastore_string_length


Try specifying that; the form_id will need to be changed to get the length
setting to be respected (you cannot simply modify the existing form
definition to add an odk:length attribute). Please let me know whether
there is an error when you attempt to upload a form with this setting and,
if not, whether or not adding it resolves the 255-character limit problem.
If it works, I will update the documentation calling this out as a concern
and work-around.


On Tue, Jul 21, 2015 at 1:03 PM, Julián R. Figueroa <
notifications@github.com> wrote:

> Hello there. I am using GeoODK with an Aggregate server in appspot. We
> have a no-required question type *geotrace* to fill a perimeter of a
> land. Sometimes people are uploading the data but this data is coming with
> missing values.
>
> Do you know if this is an issue of length of the field? or issue of the
> GeoODK app that's sending the info with some missing characters?
>
> [image: bug1]
> <https://cloud.githubusercontent.com/assets/4431392/8811144/9042cf88-2fb9-11e5-9669-c641aea8ecca.jpg>
>
> [image: bug2]
> <https://cloud.githubusercontent.com/assets/4431392/8811100/0e812e68-2fb9-11e5-82d0-15465ce7e7fe.jpg>
>
> Data is always supposed to be an array of coordinates separated by a
> semicolon, where each coordinate is a 4-value array separated by spaces.
>
> Is this an issue of Aggregate receiving/exporting the data? or an issue of
> GeoODK sending it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opendatakit/opendatakit/issues/1163>.
>



-- 
Mitch Sundt
Software Engineer
University of Washington
mitchellsundt@gmail.com

**Comment by jbeorse** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jeffisveryhungry@gmail.com
    Domain beorse.net has exceeded the max emails per hour (271/250 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:7404)
	by hp159.hostpapa.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-c877-jeff=beorse.net@sgmail.github.com>)
	id 1dgMCd-000eZo-5u
	for jeff@beorse.net; Fri, 11 Aug 2017 22:31:03 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=cHY1EtNpGVhWHbzdgAqkrF/8WkQ=; b=G9/qV9fLa+W9eqcN
	bsBuQiZq9T4koKGJ1Ez+PJndCU/0OFT/6fXJt4heiBeTM4CM/fXWGO8jXCJB42KK
	XuICa/UAYE2mA4SKtH14Rg5ekTPzYfDjdVcjrmN1SLDDMEc0hghOzmQG21g0ewsJ
	piCYRH0O1b78CVSu/geW7G/tfFE=
Received: by filter0527p1mdw1.sendgrid.net with SMTP id filter0527p1mdw1-30272-598E683E-58
        2017-08-12 02:30:22.987607214 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0005p1iad1.sendgrid.net (SG) with ESMTP id FKz2PJdXS4KKnZ1Gm5RSEw
	for <Jeff@Beorse.net>; Sat, 12 Aug 2017 02:30:22.727 +0000 (UTC)
Date: Sat, 12 Aug 2017 02:30:23 +0000 (UTC)
