### ISSUE TITLE
Apps should exit gracefully instead of crashing when Core Services is not present

### ISSUE THREAD

**Issue by marshallb93** [opendatakit/opendatakit#1164]
Instead of crashing, apps (Survey, Tables, Sync, etc) should exit, while prompting the user with a dialogue box to "Install Core Services".

I imagine it would make most sense for the required changes to go in AndroidCommon, since this is shared by all of the 2.0 tools.

**Comment by jbeorse** [comment]
Fixed or not an issue as of RC2 or earlier
