### ISSUE TITLE
ODK Validate does not validate if the variable is used before it is defined!

### ISSUE THREAD

**Issue by hjameelq** [opendatakit/opendatakit#1166]
Hi,

I couldn't upload excel file or so, but I have used here a variable before it is defined, and it didn't throw up any problem when I tried to validate the form, but the server didn't accept to upload it due to xform def problems.

Please have a look at pic attached, I 'm sorry I couldn't upload the excel file.

![odk-issue](https://cloud.githubusercontent.com/assets/11791359/9325579/11b852f2-459c-11e5-8a34-48e309cd9706.png)

**Comment by mitchellsundt** [comment]
See my attempt at duplicating this form here: 

https://drive.google.com/file/d/0ByL2Z0RJHwGaaEFodGpmUUpLck0/view?usp=sharing

This works both for uploading to ODK Aggregate and for downloading, filling out, and running.
