### ISSUE TITLE
select_multiple_external

### ISSUE THREAD

**Issue by jgrojas** [opendatakit/opendatakit#1167]
*Migrated to opendatakit/collect#181 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

Hi everyone

thanks for work in this app.  Is amazing.

I would like the select_multiple_external function in the workflow because with this somemany choices go to itemset and with this is more efficient the form.

Thanks and regards.

**Comment by mitchellsundt** [comment]
The core team has very limited resources.

We gladly accept contributed additions to the 1.x software, but we
generally don't have the time to add new features to the 1.x software
ourselves.

If you would like that feature in the tools, please consider contributing
the change yourself or hiring someone to make the changes and require them
to contribute the changes back to the main codebase.



On Tue, Aug 25, 2015 at 7:42 AM, jgrojas <notifications@github.com> wrote:

> Hi everyone
>
> thanks for work in this app. Is amazing.
>
> I would like the select_multiple_external function in the workflow because
> with this somemany choices go to itemset and with this is more efficient
> the form.
>
> Thanks and regards.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opendatakit/opendatakit/issues/1167>.
>



-- 
Mitch Sundt
Software Engineer
University of Washington
mitchellsundt@gmail.com
