### ISSUE TITLE
ODK Collect 1.4.6 (1051) crashes when getting formlist

### ISSUE THREAD

**Issue by royrutto** [opendatakit/opendatakit#1168]
ODK Collect crashes when trying to get form list if you have already have some blank forms that were downloaded previously.

![odk-crashes](https://cloud.githubusercontent.com/assets/1002419/9633183/2a258cf2-5194-11e5-875e-2eedbdd05076.png)

The stacktrace in the logs when it crashes:
```java
java.lang.NullPointerException
           at org.odk.collect.android.activities.FormDownloadList.isLocalFormSuperseded(FormDownloadList.java:597)
           at org.odk.collect.android.activities.FormDownloadList.selectSupersededForms(FormDownloadList.java:614)
           at org.odk.collect.android.activities.FormDownloadList.formListDownloadingComplete(FormDownloadList.java:683)
           at org.odk.collect.android.tasks.DownloadFormListTask.onPostExecute(DownloadFormListTask.java:263)
           at org.odk.collect.android.tasks.DownloadFormListTask.onPostExecute(DownloadFormListTask.java:44)
           at android.os.AsyncTask.finish(AsyncTask.java:631)
           at android.os.AsyncTask.access$600(AsyncTask.java:177)
           at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
           at android.os.Handler.dispatchMessage(Handler.java:99)
           at android.os.Looper.loop(Looper.java:213)
           at android.app.ActivityThread.main(ActivityThread.java:5225)
           at java.lang.reflect.Method.invokeNative(Native Method)
           at java.lang.reflect.Method.invoke(Method.java:525)
           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:741)
           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
           at dalvik.system.NativeStart.main(Native Method)
```

**Comment by mitchellsundt** [comment]
What version of Android are you running?


On Wed, Sep 2, 2015 at 7:04 AM, Roy Rutto <notifications@github.com> wrote:

> ODK Collect crashes when trying to get form list if you have already have
> some blank forms that were downloaded previously.
>
> [image: odk-crashes]
> <https://cloud.githubusercontent.com/assets/1002419/9633183/2a258cf2-5194-11e5-875e-2eedbdd05076.png>
>
> The stacktrace in the logs when it crashes:
>
> java.lang.NullPointerException
>            at org.odk.collect.android.activities.FormDownloadList.isLocalFormSuperseded(FormDownloadList.java:597)
>            at org.odk.collect.android.activities.FormDownloadList.selectSupersededForms(FormDownloadList.java:614)
>            at org.odk.collect.android.activities.FormDownloadList.formListDownloadingComplete(FormDownloadList.java:683)
>            at org.odk.collect.android.tasks.DownloadFormListTask.onPostExecute(DownloadFormListTask.java:263)
>            at org.odk.collect.android.tasks.DownloadFormListTask.onPostExecute(DownloadFormListTask.java:44)
>            at android.os.AsyncTask.finish(AsyncTask.java:631)
>            at android.os.AsyncTask.access$600(AsyncTask.java:177)
>            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
>            at android.os.Handler.dispatchMessage(Handler.java:99)
>            at android.os.Looper.loop(Looper.java:213)
>            at android.app.ActivityThread.main(ActivityThread.java:5225)
>            at java.lang.reflect.Method.invokeNative(Native Method)
>            at java.lang.reflect.Method.invoke(Method.java:525)
>            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:741)
>            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
>            at dalvik.system.NativeStart.main(Native Method)
> ``
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opendatakit/opendatakit/issues/1168>.
>



-- 
Mitch Sundt
Software Engineer
University of Washington
mitchellsundt@gmail.com

**Comment by mitchellsundt** [comment]
Please try this APK:

https://drive.google.com/file/d/0ByL2Z0RJHwGaZ3E0NmhIWVgzSTQ/view?usp=sharing

And let me know if it resolves the issue.


On Wed, Sep 2, 2015 at 9:56 AM, Mitch Sundt <mitchellsundt@gmail.com> wrote:

> What version of Android are you running?
>
>
> On Wed, Sep 2, 2015 at 7:04 AM, Roy Rutto <notifications@github.com>
> wrote:
>
>> ODK Collect crashes when trying to get form list if you have already have
>> some blank forms that were downloaded previously.
>>
>> [image: odk-crashes]
>> <https://cloud.githubusercontent.com/assets/1002419/9633183/2a258cf2-5194-11e5-875e-2eedbdd05076.png>
>>
>> The stacktrace in the logs when it crashes:
>>
>> java.lang.NullPointerException
>>            at org.odk.collect.android.activities.FormDownloadList.isLocalFormSuperseded(FormDownloadList.java:597)
>>            at org.odk.collect.android.activities.FormDownloadList.selectSupersededForms(FormDownloadList.java:614)
>>            at org.odk.collect.android.activities.FormDownloadList.formListDownloadingComplete(FormDownloadList.java:683)
>>            at org.odk.collect.android.tasks.DownloadFormListTask.onPostExecute(DownloadFormListTask.java:263)
>>            at org.odk.collect.android.tasks.DownloadFormListTask.onPostExecute(DownloadFormListTask.java:44)
>>            at android.os.AsyncTask.finish(AsyncTask.java:631)
>>            at android.os.AsyncTask.access$600(AsyncTask.java:177)
>>            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
>>            at android.os.Handler.dispatchMessage(Handler.java:99)
>>            at android.os.Looper.loop(Looper.java:213)
>>            at android.app.ActivityThread.main(ActivityThread.java:5225)
>>            at java.lang.reflect.Method.invokeNative(Native Method)
>>            at java.lang.reflect.Method.invoke(Method.java:525)
>>            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:741)
>>            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
>>            at dalvik.system.NativeStart.main(Native Method)
>> ``
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/opendatakit/opendatakit/issues/1168>.
>>
>
>
>
> --
> Mitch Sundt
> Software Engineer
> University of Washington
> mitchellsundt@gmail.com
>



-- 
Mitch Sundt
Software Engineer
University of Washington
mitchellsundt@gmail.com

**Comment by royrutto** [comment]
Using Android 4.4.2. It also happens on other versions of Android.

The APK resolves the issue. Thanks. How soon can the fix be published to Play?

**Comment by royrutto** [comment]
Just seen its alread been pushed. Thanks.
