### ISSUE TITLE
Not consistent behavior between "datetime" and "date" fields when they are used with "year" and "month-year" appearances

### ISSUE THREAD

**Issue by meletis** [opendatakit/opendatakit#1174]
Please take a look in the attached screenshot:

![image](https://cloud.githubusercontent.com/assets/654163/10602396/bbe47c00-7720-11e5-92c2-991a2e159d67.png)

This is from a form that was two "datetime" fields and two "date" fields. Each one has the "month-year" and the "year" appearance once, so we have 4 combinations (2 field types with 2 difference appearances)

Collect is not consistent here, but perhaps there is a reason. The dates that you see is my "current" timestamp; I didn't select anything, I was just swiping past all questions so the fields captured my current timestamp. (And this is how they will be exported in the Briefcase).

1. Both the "datetime" fields maintained my current month and date (Oct. 20).
2. Both the "date" fields behaved differently.
   * 2a. The first one (with the "month-year" appearance) made the date (20) be "1".
   * 2b. The second one (with the "year" appearance) made the date (20) be "1", but also the month (10) be "1". So, when a field is hidden by the appearance, it gets converted to "1" (the first day of the month or the first month of the year).

I know that 2a and 2b are intentional:

https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/widgets/DateWidget.java#L239-L250

The reason I opened this issue is why the DateTimeWidget does not behave the same? Is there a reason behind this behavior?

**Comment by mitchellsundt** [comment]
I never thought to use a month or month-year appearance on a datetime
field.

Furthermore, I didn't know that those appearance settings worked
on datetime fields!

This should probably be forced to be 00:00:00 in the time fields.

This should probably be fixed before anyone revises any of the
date/datetime handling in JR to fix the many problems in that code.


On Tue, Oct 20, 2015 at 1:56 AM, meletis <notifications@github.com> wrote:

> Please take a look in the attached screenshot:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/654163/10602396/bbe47c00-7720-11e5-92c2-991a2e159d67.png>
>
> This is from a form that was two "datetime" fields and two "date" fields.
> Each one has the "month-year" and the "year" appearance once, so we have 4
> combinations (2 field types with 2 difference appearances)
>
> Collect is not consistent here, but perhaps there is a reason. The dates
> that you see is my "current" timestamp; I didn't select anything, I was
> just swiping past all questions so the fields captured my current
> timestamp. (And this is how they will be exported in the Briefcase).
>
>    1. Both the "datetime" fields maintained my current month and date
>    (Oct. 20).
>    2. Both the "date" fields behaved differently. 2a. The first one (with
>    the "month-year" appearance) made the date (20) be "1". 2b. The second one
>    (with the "year" appearance) made the date (20) be "1", but also the month
>    (10) be "1". So, when a field is hidden by the appearance, it gets
>    converted to "1" (the first day of the month or the first month of the
>    year).
>
> I know that 2a and 2b are intentional:
>
>
> https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/widgets/DateWidget.java#L239-L250
>
> The reason I opened this issue is why the DateTimeWidget does not behave
> the same? Is there a reason behind this behavior?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opendatakit/opendatakit/issues/1174>.
>



-- 
Mitch Sundt
Software Engineer
University of Washington
mitchellsundt@gmail.com

**Comment by mitchellsundt** [comment]
...make that "year" and "month-year"

On Tue, Oct 20, 2015 at 9:14 AM, Mitch Sundt <mitchellsundt@gmail.com>
wrote:

> I never thought to use a month or month-year appearance on a datetime
> field.
>
> Furthermore, I didn't know that those appearance settings worked
> on datetime fields!
>
> This should probably be forced to be 00:00:00 in the time fields.
>
> This should probably be fixed before anyone revises any of the
> date/datetime handling in JR to fix the many problems in that code.
>
>
> On Tue, Oct 20, 2015 at 1:56 AM, meletis <notifications@github.com> wrote:
>
>> Please take a look in the attached screenshot:
>>
>> [image: image]
>> <https://cloud.githubusercontent.com/assets/654163/10602396/bbe47c00-7720-11e5-92c2-991a2e159d67.png>
>>
>> This is from a form that was two "datetime" fields and two "date" fields.
>> Each one has the "month-year" and the "year" appearance once, so we have 4
>> combinations (2 field types with 2 difference appearances)
>>
>> Collect is not consistent here, but perhaps there is a reason. The dates
>> that you see is my "current" timestamp; I didn't select anything, I was
>> just swiping past all questions so the fields captured my current
>> timestamp. (And this is how they will be exported in the Briefcase).
>>
>>    1. Both the "datetime" fields maintained my current month and date
>>    (Oct. 20).
>>    2. Both the "date" fields behaved differently. 2a. The first one
>>    (with the "month-year" appearance) made the date (20) be "1". 2b. The
>>    second one (with the "year" appearance) made the date (20) be "1", but also
>>    the month (10) be "1". So, when a field is hidden by the appearance, it
>>    gets converted to "1" (the first day of the month or the first month of the
>>    year).
>>
>> I know that 2a and 2b are intentional:
>>
>>
>> https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/widgets/DateWidget.java#L239-L250
>>
>> The reason I opened this issue is why the DateTimeWidget does not behave
>> the same? Is there a reason behind this behavior?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/opendatakit/opendatakit/issues/1174>.
>>
>
>
>
> --
> Mitch Sundt
> Software Engineer
> University of Washington
> mitchellsundt@gmail.com
>



-- 
Mitch Sundt
Software Engineer
University of Washington
mitchellsundt@gmail.com

**Comment by meletis** [comment]
Well, they are supported in datetime fields also, explicitly supported, not by accident. :)

**Comment by meletis** [comment]
Closed by accident. Re-opened.
