### ISSUE TITLE
ODK Aggregate v1.4.7 missing Permissions/Site Admin tabs

### ISSUE THREAD

**Issue by geiserc** [opendatakit/opendatakit#1175]
I've just deployed ODK Aggregate on AWS EC2 server. I can access ODK Aggregate via the IP:8080, but there is no login page and it appears I am logged in. I can upload a form that I created, and I can get ODK Collect to connect and download the form the the mobile device. When I try to upload the completed form back to ODK Aggregate I get a timeout message: "Test observation - Error: Internal Server Error (500) at http://##.#.###.##:8080/submission?deviceID=imei%...

I also have the "This server and its data are not secure! Please change the super-user's password!" warning at the top of the ODK Aggregate screen and cannot change the super-user password since the Site Admin tab is missing. The Log Out button is missing and in it's place is the Log In button - when i select that the screen times out. Note: I did change the ODKAggregate.war file name to ROOT.war.

Any thoughts on how to fix this?

Thank you,
Che 

![missing site admin](https://cloud.githubusercontent.com/assets/7979394/10707291/2a08c778-79a5-11e5-8f92-18112c55447f.jpg)
![uploaded form](https://cloud.githubusercontent.com/assets/7979394/10707295/31d10f60-79a5-11e5-9003-14df67cb6bcb.jpg)

**Comment by mitchellsundt** [comment]
Please do not use github for operational issues.

Use the opendatakit@ group/list: http://opendatakit.org/participate/

See the instructions here:

http://opendatakit.org/use/aggregate/#Using_the_Application





On Fri, Oct 23, 2015 at 4:43 PM, geiserc <notifications@github.com> wrote:

> I've just deployed ODK Aggregate on AWS EC2 server. I can access ODK
> Aggregate via the IP:8080, but there is no login page and it appears I am
> logged in. I can upload a form that I created, and I can get ODK Collect to
> connect and download the form the the mobile device. When I try to upload
> the completed form back to ODK Aggregate I get a timeout message: "Test
> observation - Error: Internal Server Error (500) at http://
> ##.#.###.##:8080/submission?deviceID=imei%...
>
> I also have the "This server and its data are not secure! Please change
> the super-user's password!" warning at the top of the ODK Aggregate screen
> and cannot change the super-user password since the Site Admin tab is
> missing. The Log Out button is missing and in it's place is the Log In
> button - when i select that the screen times out. Note: I did change the
> ODKAggregate.war file name to ROOT.war.
>
> Any thoughts on how to fix this?
>
> Thank you,
> Che
>
> [image: missing site admin]
> <https://cloud.githubusercontent.com/assets/7979394/10707291/2a08c778-79a5-11e5-8f92-18112c55447f.jpg>
> [image: uploaded form]
> <https://cloud.githubusercontent.com/assets/7979394/10707295/31d10f60-79a5-11e5-9003-14df67cb6bcb.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opendatakit/opendatakit/issues/1175>.
>



-- 
Mitch Sundt
Software Engineer
University of Washington
mitchellsundt@gmail.com

**Comment by mitchellsundt** [comment]
Closing this - operational and usage issues should not use this mechanism.
