### ISSUE TITLE
ODK Aggregate setup - 404 on Tomcat Server

### ISSUE THREAD

**Issue by MartinInghamBF** [opendatakit/opendatakit#1178]
Hi, I am struggling with the configuration and setup files for getting the ODK Aggregate source runnable.  I am stuck on step 6 in the Setup.txt instructions in eclipse-aggregate-mysql.
Step 5 - I've assumed "this project" refers to eclipse-aggregate-mysql, is that correct?
Step 6 - I'm not clear on this instruction.  I've added a second Tomcat Server 6 to Eclipse (Window > Preferences > Server > Runtime Environment) with the installed JRE 7 as the JRE, is that correct?  I don't understand the second sentence.
I now have two Tomcat 6 servers in the Servers section. If I start either of these and browse to 127.0.0.1:8080/ODKAggregate, I get a 404 from Tomcat after the redirect to ODKAggregate/Aggregate.html.  What am I doing wrong?
To clarify - all previous steps are working, it runs OK under Jetty.  I have tried both 127.0.0.1 and the computer's FQDN in security.server.hostname.

**Comment by mitchellsundt** [comment]
**Please use the opendatakit-developers@ list for questions about building the source code.  Issues are not a good mechanism for resolving these problems.**

Step 5: yes

Step 6:  delete the original server runtime environment. It is likely that some part of your project settings is incorrectly depending upon it. Use the one you've added. The one you added should point at the Tomcat 6 server installation and JRE that you set up in step 3.  

Is the URL correct after the redirect?  It sounds like the hostname or port in the settings jar is not set correctly. Verify that you have a fully working Tomcat 6 install of Aggregate (from the installer) working and that you can log in and interact with the server.  Then stop that server, and copy the the settings into your Eclipse environment, refresh, and try launching it.
