### ISSUE TITLE
Collect: Cascading select demo forms cause crash

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/opendatakit#1179]
*Migrated to opendatakit/collect#188 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

Both Cascading Select and Cascading Triple Select demo forms seem to cause crashes and weird behavior on Collect. Seems to happen on second open.

**Comment by meletis** [comment]
Is it possible that #1180 is the same issue?
