### ISSUE TITLE
apk not run in all samsung device

### ISSUE THREAD

**Issue by snaju2145** [opendatakit/opendatakit#1182]
i download the collect source code and run project it deploy successfully  apk, this apk successfully run in all device but can not run in all samsung device why...?

**Comment by snaju2145** [comment]
please help me

**Comment by mitchellsundt** [comment]
Closing this -- please use the opendatakit-developers@ list for questions of this nature.  See https://opendatakit.org/participate/

e.g., https://groups.google.com/forum/#!forum/opendatakit-developers
