### ISSUE TITLE
Form Tamper Detection Preload Function

### ISSUE THREAD

**Issue by solalxv** [opendatakit/opendatakit#1183]
Scenario: User finalices form in ODK collect, then using an external text editor the user changes data in the xml file avoiding all form restrictions.

I will be posible to add a precalculated CRC function in ODK Collect in order to detect modifications outside the application?

In example:
```
<bind nodeset="/widgets/my_crc" type="string" 
 jr:preload="property" 
 jr:preloadParams="mycrcfunction"/>
```

The algoritm or function should be configurable, with this precalculated field we could be able to determine if the data was changed after the form finalization.

Initially This CRC field only would be valid for the xml file itself and not for the media attachments, the main goal is not to encrypt the form, the main purpose is tamper detection once the form is delivered.

Thank you

**Comment by mitchellsundt** [comment]
This is problematic and the change would not be accepted. 

There is nothing to prevent the external tool from re-computing this CRC function.  I.e., the proposed enhancement only prevents simplistic tampering attempts, not skilled ones.  

A more appropriate solution would leverage user profiles that have restricted access to applications on the device (i.e., no editors), disable USB and developer access to the device, and encrypt the device and external SD Card (if removable) to prevent it from being removed and its contents modified.
