### ISSUE TITLE
Video capture crashes video app on Android 6.0 on Nvidia Shield K1 Tablet

### ISSUE THREAD

**Issue by ni-ka** [opendatakit/opendatakit#1189]
*Migrated to opendatakit/collect#190 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

A colleague of mine is trying to use ODK collect (4.3) on an Nvidia Shield 8-Inch Tablet K1.

The device was running on Android 5 and after recording a video it gave a java Exception "An error occurred while attaching the media: ". Recording the video seemed to work correctly but it was not added to the form.

Before filing a bug, I recommended to install a pending Android update. Under Android 6.0 after recording the video a black screeen is displayed with a Play, Check (ok) and Cross (cancel) icon. None of the icons can be pressed and after a while the message "Shield Camera isn't responding. Do you want to close it?" is displayed.

**Comment by mitchellsundt** [comment]
The pre-update issue is definitely in ODK Collect. If this happens again, see https://github.com/opendatakit/opendatakit/wiki/Collect-Troubleshooting for how to collect a log (or if it is installed via Google Play, the user can choose to send us a crash report). Attach that log if you get one.

After the update, the error seems to be in the camera application, as that screen is part of the camera app (nothing like it exists within ODK Collect).
