### ISSUE TITLE
Copy/paste using long-press on text field

### ISSUE THREAD

**Issue by Gkreindler** [opendatakit/opendatakit#1194]
*Migrated to opendatakit/collect#191 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

Currently, long press on a text field opens a menu to "edit prompt / remove response". It would be helpful to be able to paste a string, and possibly also to copy its existing contents. 

Can the copy/paste options be added to the long press menu for text fields?

This issue came up recently:
https://groups.google.com/forum/#!topic/opendatakit/f9nINg8x81Y
I encountered the same issue when I needed to copy a location from Google Maps to clipboard, and paste it in an ODK question.

**Comment by andris** [comment]
+1 - this would be really helpful!

**Comment by adzucker** [comment]
+1, this would be useful when using other applications alongside ODK.
