### ISSUE TITLE
Aggregate loses data if submission batches are not sequential

### ISSUE THREAD

**Issue by MartijnR** [opendatakit/opendatakit#1195]
Note: I tested this with ODK Aggregate **v1.4.5**. My user experienced this issue in v1.4.6. If Aggregate's (batches) submission handling has been updated in v1.4.7, please accept my apologies and discard this issue. (I don't seem to be capable of updating Aggregate any more).

If a submission contains two 9Mb images (I used the same image with different filenames), the submission is split up into 2 batches. I found that if both batches are sent in close succession, i.e. the second batch is sent before the first batch submission has received a response from Aggregate, Aggregate returns a 201 response for both batches. **This indicates to the client the record was received successfully.**

<img width="594" alt="screen shot 2016-02-02 at 4 31 47 pm" src="https://cloud.githubusercontent.com/assets/627350/12792234/198775ca-ca68-11e5-86ce-9da367782a3b.png">

It seems that the record is not available in Aggregate though and I see an error like this:

<img width="437" alt="screen shot 2016-02-02 at 2 27 47 pm" src="https://cloud.githubusercontent.com/assets/627350/12792030/1a927cd6-ca67-11e5-90b7-c6baff97a200.png">

The OpenRosa submission spec doesn't specify that these batches need to be sent sequentially. Ona doesn't require this either (and presumably nor do KoBo and Formhub).

As a workaround Enketo now sends batches sequentially. However, considering the serious consequences (permanent data loss?) of this bug, I wanted to report it.

**Comment by jbeorse** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jeffisveryhungry@gmail.com
    Domain beorse.net has exceeded the max emails per hour (273/250 (109%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:42637)
	by hp159.hostpapa.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-c877-jeff=beorse.net@sgmail.github.com>)
	id 1dgMCf-000eaF-Aj
	for jeff@beorse.net; Fri, 11 Aug 2017 22:31:05 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=I5NT0qU7sc7SS8z2oug4PIInUck=; b=HiJfn5keHiRXuc8K
	VvQ9nGTTKmAPZo21sp9RTHDsSHwIt5bjUn70Cc8Z5y72II18h7nNUdZsW+sT1ZAu
	5wtS5TuhwQQEe7ZbztoH0i5AKOO23ckcFU55LeWRv5BF0mBqUB7gh41EmEboMg0a
	K6GHd3qzexK7traQB+Vh6UE+kWU=
Received: by filter0930p1mdw1.sendgrid.net with SMTP id filter0930p1mdw1-31664-598E6841-4E
        2017-08-12 02:30:25.65219349 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0024p1mdw1.sendgrid.net (SG) with ESMTP id M1jD0NJwRsGJsEgGKJXVXA
	for <Jeff@Beorse.net>; Sat, 12 Aug 2017 02:30:25.607 +0000 (UTC)
Date: Sat, 12 Aug 2017 02:30:25 +0000 (UTC)
