### ISSUE TITLE
Build fail,but not when running collect (development)

### ISSUE THREAD

**Issue by moychal** [opendatakit/opendatakit#1198]
When I just do Build -> Make Project on collect (development branch), I get: #

Error:Execution failed for task ':collect_app:processDebugAndroidTestManifest'.
> java.lang.RuntimeException: Manifest merger failed : uses-sdk:minSdkVersion 8 cannot be smaller than version 13 declared in library [com.android.support:support-v13:23.1.0] C:\Users\Michael\StudioProjects\collect\collect_app\build\intermediates\exploded-aar\com.android.support\support-v13\23.1.0\AndroidManifest.xml
	Suggestion: use tools:overrideLibrary="android.support.v13" to force usage

Although when running it, it builds successfully.

**Comment by mitchellsundt** [comment]
These issues should be raised on the support list opendatakit-developers@
