### ISSUE TITLE
Aggregate doesn't start

### ISSUE THREAD

**Issue by stevensotelo** [opendatakit/opendatakit#1199]
I was following the step by step to deploy aggregate in AWS, but doesn't work. 
I the following configuration:

* mysql database
* tomcat 6

I deployed the ROOT.war in /usr/share/tomcat6/ 

The following is the message of the tomcat log:

Feb 23, 2016 7:56:51 PM org.apache.catalina.core.AprLifecycleListener init
INFO: The APR based Apache Tomcat Native library which allows optimal performanc
e in production environments was not found on the java.library.path: /usr/java/p
ackages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
Feb 23, 2016 7:56:51 PM org.apache.coyote.http11.Http11Protocol init
INFO: Initializing Coyote HTTP/1.1 on http-8080
Feb 23, 2016 7:56:51 PM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 833 ms
Feb 23, 2016 7:56:51 PM org.apache.catalina.core.StandardService start
INFO: Starting service Catalina
Feb 23, 2016 7:56:51 PM org.apache.catalina.core.StandardEngine start
INFO: Starting Servlet Engine: Apache Tomcat/6.0.44
Feb 23, 2016 7:56:51 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive ROOT.war
Feb 23, 2016 7:59:03 PM org.apache.catalina.core.StandardContext start
SEVERE: Error listenerStart
Feb 23, 2016 7:59:03 PM org.apache.catalina.core.StandardContext start
SEVERE: Context [] startup failed due to previous errors
Feb 23, 2016 7:59:03 PM org.apache.catalina.loader.WebappClassLoader clearRefere
ncesThreads
SEVERE: The web application [] appears to have started a thread named [Abandoned
 connection cleanup thread] but has failed to stop it. This is very likely to cr
eate a memory leak.
Feb 23, 2016 7:59:04 PM org.apache.coyote.http11.Http11Protocol start
INFO: Starting Coyote HTTP/1.1 on http-8080
Feb 23, 2016 7:59:04 PM org.apache.jk.common.ChannelSocket init
INFO: JK: ajp13 listening on /0.0.0.0:8009
Feb 23, 2016 7:59:04 PM org.apache.jk.server.JkMain start
INFO: Jk running ID=0 time=0/111  config=null
Feb 23, 2016 7:59:04 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 132920 ms
Feb 23, 2016 8:24:09 PM org.apache.coyote.http11.Http11Protocol pause
INFO: Pausing Coyote HTTP/1.1 on http-8080
Feb 23, 2016 8:24:10 PM org.apache.catalina.core.StandardService stop
INFO: Stopping service Catalina
Feb 23, 2016 8:24:10 PM org.apache.coyote.http11.Http11Protocol destroy
INFO: Stopping Coyote HTTP/1.1 on http-8080
Feb 23, 2016 8:25:34 PM org.apache.catalina.core.AprLifecycleListener init
INFO: The APR based Apache Tomcat Native library which allows optimal performanc
e in production environments was not found on the java.library.path: /usr/java/p
ackages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
Feb 23, 2016 8:25:35 PM org.apache.coyote.http11.Http11Protocol init
INFO: Initializing Coyote HTTP/1.1 on http-8080
Feb 23, 2016 8:25:35 PM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 1442 ms
Feb 23, 2016 8:25:35 PM org.apache.catalina.core.StandardService start
Feb 23, 2016 8:25:35 PM org.apache.catalina.core.StandardService start
INFO: Starting service Catalina
Feb 23, 2016 8:25:35 PM org.apache.catalina.core.StandardEngine start
INFO: Starting Servlet Engine: Apache Tomcat/6.0.44
Feb 23, 2016 8:25:35 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive ROOT.war
Feb 23, 2016 8:27:47 PM org.apache.catalina.core.StandardContext start
SEVERE: Error listenerStart
Feb 23, 2016 8:27:47 PM org.apache.catalina.core.StandardContext start
SEVERE: Context [] startup failed due to previous errors
Feb 23, 2016 8:27:47 PM org.apache.catalina.loader.WebappClassLoader clearRefere
ncesThreads
SEVERE: The web application [] appears to have started a thread named [Abandoned
 connection cleanup thread] but has failed to stop it. This is very likely to cr
eate a memory leak.
Feb 23, 2016 8:27:48 PM org.apache.coyote.http11.Http11Protocol start
INFO: Starting Coyote HTTP/1.1 on http-8080
Feb 23, 2016 8:27:48 PM org.apache.jk.common.ChannelSocket init
INFO: JK: ajp13 listening on /0.0.0.0:8009
Feb 23, 2016 8:27:48 PM org.apache.jk.server.JkMain start
INFO: Jk running ID=0 time=0/17  config=null
Feb 23, 2016 8:27:48 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 133087 ms

Thanks for your help

**Comment by mitchellsundt** [comment]
*SEVERE: Error listenerStart*

Please ask these questions on the opendatakit@ list, and not in GitHub.

This error would indicate that the Tomcat webserver was unable to open port
8080 because some other application on your server has already opened that
port.  Because these ports can only be opened by one application at a time,
you need to change the server configuration so that either the other
application is not started or Tomcat uses a different port.  Use ss and/or
netstat http://linux.die.net/man/8/netstat to discover what other app
already claimed that port.



On Tue, Feb 23, 2016 at 12:34 PM, Steven Sotelo <notifications@github.com>
wrote:

> I was following the step by step to deploy aggregate in AWS, but doesn't
> work.
> I the following configuration:
>
>    - mysql database
>    - tomcat 6
>
> I deployed the ROOT.war in /usr/share/tomcat6/
>
> The following is the message of the tomcat log:
>
> Feb 23, 2016 7:56:51 PM org.apache.catalina.core.AprLifecycleListener init
> INFO: The APR based Apache Tomcat Native library which allows optimal
> performanc
> e in production environments was not found on the java.library.path:
> /usr/java/p
> ackages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
> Feb 23, 2016 7:56:51 PM org.apache.coyote.http11.Http11Protocol init
> INFO: Initializing Coyote HTTP/1.1 on http-8080
> Feb 23, 2016 7:56:51 PM org.apache.catalina.startup.Catalina load
> INFO: Initialization processed in 833 ms
> Feb 23, 2016 7:56:51 PM org.apache.catalina.core.StandardService start
> INFO: Starting service Catalina
> Feb 23, 2016 7:56:51 PM org.apache.catalina.core.StandardEngine start
> INFO: Starting Servlet Engine: Apache Tomcat/6.0.44
> Feb 23, 2016 7:56:51 PM org.apache.catalina.startup.HostConfig deployWAR
> INFO: Deploying web application archive ROOT.war
> Feb 23, 2016 7:59:03 PM org.apache.catalina.core.StandardContext start
> SEVERE: Error listenerStart
> Feb 23, 2016 7:59:03 PM org.apache.catalina.core.StandardContext start
> SEVERE: Context [] startup failed due to previous errors
> Feb 23, 2016 7:59:03 PM org.apache.catalina.loader.WebappClassLoader
> clearRefere
> ncesThreads
> SEVERE: The web application [] appears to have started a thread named
> [Abandoned
> connection cleanup thread] but has failed to stop it. This is very likely
> to cr
> eate a memory leak.
> Feb 23, 2016 7:59:04 PM org.apache.coyote.http11.Http11Protocol start
> INFO: Starting Coyote HTTP/1.1 on http-8080
> Feb 23, 2016 7:59:04 PM org.apache.jk.common.ChannelSocket init
> INFO: JK: ajp13 listening on /0.0.0.0:8009
> Feb 23, 2016 7:59:04 PM org.apache.jk.server.JkMain start
> INFO: Jk running ID=0 time=0/111 config=null
> Feb 23, 2016 7:59:04 PM org.apache.catalina.startup.Catalina start
> INFO: Server startup in 132920 ms
> Feb 23, 2016 8:24:09 PM org.apache.coyote.http11.Http11Protocol pause
> INFO: Pausing Coyote HTTP/1.1 on http-8080
> Feb 23, 2016 8:24:10 PM org.apache.catalina.core.StandardService stop
> INFO: Stopping service Catalina
> Feb 23, 2016 8:24:10 PM org.apache.coyote.http11.Http11Protocol destroy
> INFO: Stopping Coyote HTTP/1.1 on http-8080
> Feb 23, 2016 8:25:34 PM org.apache.catalina.core.AprLifecycleListener init
> INFO: The APR based Apache Tomcat Native library which allows optimal
> performanc
> e in production environments was not found on the java.library.path:
> /usr/java/p
> ackages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
> Feb 23, 2016 8:25:35 PM org.apache.coyote.http11.Http11Protocol init
> INFO: Initializing Coyote HTTP/1.1 on http-8080
> Feb 23, 2016 8:25:35 PM org.apache.catalina.startup.Catalina load
> INFO: Initialization processed in 1442 ms
> Feb 23, 2016 8:25:35 PM org.apache.catalina.core.StandardService start
> Feb 23, 2016 8:25:35 PM org.apache.catalina.core.StandardService start
> INFO: Starting service Catalina
> Feb 23, 2016 8:25:35 PM org.apache.catalina.core.StandardEngine start
> INFO: Starting Servlet Engine: Apache Tomcat/6.0.44
> Feb 23, 2016 8:25:35 PM org.apache.catalina.startup.HostConfig deployWAR
> INFO: Deploying web application archive ROOT.war
> Feb 23, 2016 8:27:47 PM org.apache.catalina.core.StandardContext start
> SEVERE: Error listenerStart
> Feb 23, 2016 8:27:47 PM org.apache.catalina.core.StandardContext start
> SEVERE: Context [] startup failed due to previous errors
> Feb 23, 2016 8:27:47 PM org.apache.catalina.loader.WebappClassLoader
> clearRefere
> ncesThreads
> SEVERE: The web application [] appears to have started a thread named
> [Abandoned
> connection cleanup thread] but has failed to stop it. This is very likely
> to cr
> eate a memory leak.
> Feb 23, 2016 8:27:48 PM org.apache.coyote.http11.Http11Protocol start
> INFO: Starting Coyote HTTP/1.1 on http-8080
> Feb 23, 2016 8:27:48 PM org.apache.jk.common.ChannelSocket init
> INFO: JK: ajp13 listening on /0.0.0.0:8009
> Feb 23, 2016 8:27:48 PM org.apache.jk.server.JkMain start
> INFO: Jk running ID=0 time=0/17 config=null
> Feb 23, 2016 8:27:48 PM org.apache.catalina.startup.Catalina start
> INFO: Server startup in 133087 ms
>
> Thanks for your help
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opendatakit/opendatakit/issues/1199>.
>



-- 
Mitch Sundt
Software Engineer
University of Washington
mitchellsundt@gmail.com
