### ISSUE TITLE
Mistake in XML form definition documentation?

### ISSUE THREAD

**Issue by alxndrsn** [opendatakit/opendatakit#1200]
In the following example, it says it is expecting dates _after today_, and _only future dates_.  However, the operator is greater-than-**or-equal**.  Should the operator instead be a simple **greater-than** to avoid matching today's date?

> #### Constraints: Answer must be after today
>
>     <bind nodeset="/widgets/date" type="date" 
>       constraint=". >= today()" 
>       jr:constraintMsg="only future dates allowed"/>
> 
> — https://opendatakit.org/help/form-design/binding/

**Comment by mitchellsundt** [comment]
Yes! Thanks. Similar problem with the example immediately above this one. 
Both have been corrected.

**Comment by alxndrsn** [comment]
:+1: thanks!
