### ISSUE TITLE
Some typo`s in ODK Briefcase Page

### ISSUE THREAD

**Issue by cholpona** [opendatakit/opendatakit#1201]
Hi,
I going through  [ODK Briefcase Page](https://opendatakit.org/use/briefcase/) and found some places where text was duplicating.
In Installation :
2. **Navigate to Navigate to** downloads/download-category/briefcase/ and download ODK Briefcase vN.N.N.jar.

In Usage:

When pulling forms from ODK Aggregate, you can either leave the username blank if the anonymousUser is granted Data Viewer permissions, or specify an ODK Aggregate user (Account Type 'ODK') that has been granted Data Viewer permissions. ODK Briefcase does not work with Google accounts (Account Type 'Google').

When pushing forms to ODK Aggregate, you can either leave the username blank if the anonymousUser is granted Form Manager permissions, or specify an ODK Aggregate user (Account Type 'ODK') that has been granted Form Manager permissions. ODK Briefcase does not work with Google accounts (Account Type 'Google').

Best Regards,

**Comment by mitchellsundt** [comment]
Thanks. Made the change.
