### ISSUE TITLE
problem compiling android common locally

### ISSUE THREAD

**Issue by wbrunette** [opendatakit/opendatakit#1202]
when everything starts to compile and explode the names get really long

Error:Execution failed for task ':androidcommon:androidcommon_lib:mergeDebugResources'.

> C:\Users\xxxxx\SecondaryStudioProjects\androidcommon\androidcommon_lib\build\intermediates\exploded-aar\org.opendatakit\google-play-services-ODK-SNAPSHOT_lib\b201601261442_vbd27bcd\res\drawable-xhdpi-v4\common_signin_btn_text_focus_light.9.png: Error: File path too long on Windows, keep below 240 characters : C:\Users\xxxxx\SecondaryStudioProjects\androidcommon\androidcommon_lib\build\intermediates\exploded-aar\org.opendatakit\google-play-services-ODK-SNAPSHOT_lib\b201601261442_vbd27bcd\res\drawable-xhdpi-v4\common_signin_btn_text_focus_light.9.png

**Comment by mitchellsundt** [comment]
Is this from the gradle command line?

My path prefix is D:\workspace\toolsuite\  
And haven't had trouble with gradle command line builds. 
I guess I have been lucky...
