### ISSUE TITLE
Tables 2.0 rev200 - map view not working as it did in rev126

### ISSUE THREAD

**Issue by chegeiser** [opendatakit/opendatakit#1203]
Hi,

First off - I _really _appreciate all the effort the ODK team (and users!) have put into making this terrific tool! Thank you!

I  just installed the newly uploaded rev200 group of apps and loaded up the default Application Designer set of tables. When I went into the Geotagger table map view and select a point on the map the data point (Description) associated with that map point no longer jumps to the top of the list. This makes it so that you can't figure out which point on the map is associated with which item in the database view the map interface.

Seems like a likely bug in the map implementation. Any help would be appreciated.

Thank you,
Che Geiser

**Comment by chegeiser** [comment]
I also just noticed that the image thumbnails do not show up when you are on map view and select an item, when you select the area where the thumbnail should show up it takes you to the details screen but the image doesn't show up there either.

**Comment by clarlars** [comment]
Thank you for experimenting with our latest distribution.  I will definitely take a look at this issue.

**Comment by chegeiser** [comment]
Update - the images do show up, I made edits that apparently prevented them from showing up. The original issue in the first post is real though.

**Comment by clarlars** [comment]
This issue was fixed in commit 0057eb973c07d22990b1e058b1ba9b725d0522c4.

**Comment by chegeiser** [comment]
Hi Clarice,
Is the only way to add the fix listed in the commit to complie from a Github clone? No way to edit the file installed on the device? I ask because I'm not a programmer and the whole cloning and compiling is pretty far over my head, but I'm perfectly capable of entering the mods listed in the commit.

If there is no way other than compiling, do you have any idea how long it might be before the ODK team might publish an update to the apk file on opendatakit.org?

Thank you for all the help!
Che

**Comment by clarlars** [comment]
Hi Che,

You are correct.  The only way to currently get the fix is to clone the
source code and compile a new APK.

We plan on putting up another set of APKs in the next week or two.

Thank you for providing feedback on the 2.0 tools.

Clarice

**Comment by geiserc** [comment]
Thank you so much for all the help!

Che Geiser  l  Director of Asset Management l  BlueOakEnergy<http://www.blueoakenergy.com/>.com
o  (530) 747-2026 x 233  l  c  (530) 400-8033

This e-mail and any attachments thereto may contain confidential information and/or information protected by intellectual property rights for the exclusive attention of the intended addressees named above. All rights in the materials are reserved. If you have received this transmission in error, please immediately notify the sender by return e-mail and delete this message and its attachments. Unauthorized use, copying or further full or partial distribution of this e-mail or its contents is prohibited.

**Comment by jbeorse** [comment]
Hi Che,

We have just posted new binaries. The previous version was "rev 200a", which we designate as an "in progress" release. The next version is "rev 200b", which is the next iteration, but still in progress. Eventually (hopefully soon) we will release a full "rev 200" with no modifier. 

The new versions should include this fix along with other bug fixes and improvements. Please note that the default application name has been changed from the tool name (e.g. "tables" or "survey") to a unified "default" for all tools. This is also reflected in the grunt command in app-designer: 
*grunt adbpush-tables-app" is now "grunt adbpush-default-app". You may need to rename the folder inside your opendatakit directory on your devices. Also, if you are using Aggregate, you may need to update your app name there.
