### ISSUE TITLE
Tables 2.0 rev200 - choosing an image causes Tables (Survey?) to crash

### ISSUE THREAD

**Issue by chegeiser** [opendatakit/opendatakit#1204]
A possible bug in the just released rev200 ODK apps:

I've loaded the default set of files contained in  ODK ApplicationDesigner v2.0 (grunt adbpush-tables-app) to a clean install of the new Tables/Survey/Services apps. The apps all seem to load correctly. 

However, when I add a new instance to Geotagger and try to 'Choose Picture' ODK Survey crashes.

**Comment by chegeiser** [comment]
I've found note that choosing an image works fine if the image is in internal memory but crashes if the image is in external memory (memory card).

**Comment by clarlars** [comment]
Thank you for reporting the issue.  

I have not been able to reproduce the issue on an Android 4.4 tablet.  What version of Android are you running?  Is the crash independent of the location on the sdcard?

**Comment by chegeiser** [comment]
I'm on 5.1.1. I tried from external sd/DCIM/100ANDRO as well as from the root of the external sd card. Both cause a crash.

It's not a big problem as I can just use the internal memory, but it could be a problem if others encounter this and don't figure out the solution.

**Comment by clarlars** [comment]
I have not been able to reproduce this issue on a Samsung Galaxy S5 with Android version 5.0.  If you could follow the directions at https://github.com/opendatakit/opendatakit/wiki/Collect-Troubleshooting and provide me with a crash log, that would be great.  I will also continue to try to reproduce the issue.  Thank you for all of you assistance.

**Comment by chegeiser** [comment]
Logfile is attached.
[logfile.txt](https://github.com/opendatakit/opendatakit/files/168160/logfile.txt)

**Comment by jbeorse** [comment]
Fixed or not an issue as of RC2 or earlier
