### ISSUE TITLE
select_one_dropdown opens, then closes - ODK 2.0 rev200

### ISSUE THREAD

**Issue by chegeiser** [opendatakit/opendatakit#1205]
When I have a select_one_dropdown pulling choices from 'choices' tab or from a query from a csv file when I select the dropdown in order to choose a value it opens, pauses, then closes. If I select it again then I am able to choose a value from the dropdown list.

Related as it is a dropdown issue. If you don't enter a placeholder as the first value in the dropdown list choices, something like 'Select One', then it appears that the first item is by default already selected. In fact, you must choose a different item, then open the dropdown menu again and select the first item - though it appears at the head of the list it is not in fact selected in the beginning.

I can forward the form folder xlsx if that would make it easier to see what I am talking about.

Thank you for any assistance you can provide!

Logfile is attached.
[logfile.txt](https://github.com/opendatakit/opendatakit/files/168155/logfile.txt)

**Comment by jbeorse** [comment]
Fixed or not an issue as of RC2 or earlier
