### ISSUE TITLE
text too small - ODK 2.0 rev200

### ISSUE THREAD

**Issue by chegeiser** [opendatakit/opendatakit#1206]
I've found that the page rendering on my smartphone is different than it used to be on the rev126 version. The text is now very small, and the interface frequently zooms in on it's own requiring me to zoom back out in order to select next or see what is written on the page.

The screenshot below shows the zoom in/out buttons and the extent of zooming that is automatically done in the app when I select a field to enter data.

![screenshot_2016-03-09-17-22-48](https://cloud.githubusercontent.com/assets/17602493/13688964/29e78d0e-e6da-11e5-9414-7f3f217d1424.png)

**Comment by chegeiser** [comment]
I've been having this problem on multiple devices. Here's what the default demo tables home screen looks like. I've got a pen in the photo so you can see how small the text is - illegible. The problem exists on both Android 5.x and 6.x.

![img_2516](https://cloud.githubusercontent.com/assets/17602493/14749281/796492ae-0873-11e6-898e-21559452df89.JPG)

**Comment by clarlars** [comment]
Thanks for pointing this out.  We have noticed UI differences and will be
addressing these discrepancies.

Thanks,
Clarice

**Comment by chegeiser** [comment]
I think the pixel density might be the crux of this issue. In css % can be used for width and height instead of pixel values. Perhaps that might be a better way to deal with the great variety of mobile screens that have differing pixel densities?

**Comment by chegeiser** [comment]
Fixed in v204.
