### ISSUE TITLE
Start/stop time has the same date even if it is finished the day after. 

### ISSUE THREAD

**Issue by ethan92429** [opendatakit/opendatakit#1208]
*Migrated to opendatakit/collect#193 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

We collect both the start time and the finish time on the form. We received a submission that said the form was started at 11:56PM on Mar 4th, and finished at 12:05 AM on Mar 4th. Obviously the second date should be March fifth. We made our form with the ODK build online form building tool.

**Comment by mitchellsundt** [comment]
Was Mar 4th / 5th a daylight savings time transition in this time zone?
