### ISSUE TITLE
Collect doesn't display server messages

### ISSUE THREAD

**Issue by dodumosu** [opendatakit/opendatakit#1209]
*Migrated to opendatakit/collect#194 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

We're using ODK Collect for a project and have our own custom server (i.e, not Aggregate), and we return server messages in the `<message>` element of the OpenRosa document returned to ODK Collect. However, I've noticed that the messages we return to the client aren't displayed on the mobile devices.

By way of explanation, when our forms are updated, they're assigned a new UUID value as a version marker of sorts. When someone sends in a submission and the version marker is different between the submitted form and the server form, we want the sender to know that there's a version mismatch, and so we send a message, but it's not displayed on the device.

If there's any other way to get ODK Collect to display server responses, I'll be happy to find out.

Thanks for all the great work.

**Comment by mitchellsundt** [comment]
This would require a code modification.

If you provide a patch with the change, we can integrate it into the main
code tree.

Any patch should use a General Setting to show (the behavior you are
requesting) or hide (current behavior) the message after submitting data.
Note that submissions can be split across multiple HTTP requests (when
there are more than 10MB of image/audio/video attachments), so this change
would need to handle that submission-splitting behavior properly.

In general, we have found that keeping the interaction simple for the field
workers is best; for that reason, we decided to not display any
informational messages, but to simply report success or failure.



On Tue, Mar 15, 2016 at 6:32 AM, dodumosu <notifications@github.com> wrote:

> We're using ODK Collect for a project and have our own custom server (i.e,
> not Aggregate), and we return server messages in the <message> element of
> the OpenRosa document returned to ODK Collect. However, I've noticed that
> the messages we return to the client aren't displayed on the mobile devices.
>
> By way of explanation, when our forms are updated, they're assigned a new
> UUID value as a version marker of sorts. When someone sends in a submission
> and the version marker is different between the submitted form and the
> server form, we want the sender to know that there's a version mismatch,
> and so we send a message, but it's not displayed on the device.
>
> If there's any other way to get ODK Collect to display server responses,
> I'll be happy to find out.
>
> Thanks for all the great work.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/opendatakit/opendatakit/issues/1209
>



-- 
Mitch Sundt
Software Engineer
University of Washington
mitchellsundt@gmail.com
