### ISSUE TITLE
SEARCH AND SELECT IN ODK XLS FORM....

### ISSUE THREAD

**Issue by Ahsan1328** [opendatakit/opendatakit#1210]
Dear All,

Please help me regarding one thing i have a xls form which i run through formhub i want to make a search option in my xls form so that when i person select the option in pop listing listed on route after that a search bar will appear and he/she will write the POP code in it so that after forwarding the form only that POP will appear for which he wrote the code, as it is very difficult to see thousands of POP CODES in POP list.

Kindly help me out regarding this issue, i have also attached the xls form please make edit in it & reupload.

Thanks....
[POP LISTING.xlsx](https://github.com/opendatakit/opendatakit/files/175382/POP.LISTING.xlsx)

**Comment by mitchellsundt** [comment]
Note that formhub may not support external itemsets in the same way that
ODK Aggregate and ODK Collect do. If you have trouble with that, ask on
their support list.

Otherwise, see https://opendatakit.org/help/form-design/external-itemsets/



On Tue, Mar 15, 2016 at 11:33 PM, Ahsan1328 <notifications@github.com>
wrote:

> Dear All,
>
> Please help me regarding one thing i have a xls form which i run through
> formhub i want to make a search option in my xls form so that when i person
> select the option in pop listing listed on route after that a search bar
> will appear and he/she will write the POP code in it so that after
> forwarding the form only that POP will appear for which he wrote the code,
> as it is very difficult to see thousands of POP CODES in POP list.
>
> Kindly help me out regarding this issue, i have also attached the xls form
> please make edit in it & reupload.
>
> Thanks....
> POP LISTING.xlsx
> <https://github.com/opendatakit/opendatakit/files/175382/POP.LISTING.xlsx>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/opendatakit/opendatakit/issues/1210>
>



-- 
Mitch Sundt
Software Engineer
University of Washington
mitchellsundt@gmail.com

**Comment by mitchellsundt** [comment]
Closing this issue. It is best to ask questions on opendatakit@ group.
