### ISSUE TITLE
Tables crashes when adding a row from Map View

### ISSUE THREAD

**Issue by linl33** [opendatakit/opendatakit#1212]
Tables crashes when adding a row from Map View.

**Steps to reproduce**
1. Go to Map View
2. Hold on a point on Map View
3. Choose "ADD" when prompted

![device-2016-03-18-115900](https://cloud.githubusercontent.com/assets/8204095/13888970/575546f0-ed01-11e5-8e42-a8b8e98a5e11.png)

**Comment by jbeorse** [comment]
Fixed or not an issue as of RC2 or earlier
