### ISSUE TITLE
How to clear forms in the "Fill Blank Form" section of ODK Collect?

### ISSUE THREAD

**Issue by mnara299161** [opendatakit/opendatakit#1214]
I accidentally uploaded two of the same forms in Get Blank Form and now they appear in Fill Blank Form. I want to delete the extra form for a cleaner look. I am having difficulties.

**Comment by mitchellsundt** [comment]
Choose "Delete Saved Form"
choose the "Blank Forms" tab,
select the form definition you want to remove.
Choose "Delete Selected"


On Fri, Apr 1, 2016 at 2:21 PM, mnara299161 <notifications@github.com>
wrote:

> I accidentally uploaded two of the same forms in Get Blank Form and now
> they appear in Fill Blank Form. I want to delete the extra form for a
> cleaner look. I am having difficulties.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/opendatakit/opendatakit/issues/1214>
>



-- 
Mitch Sundt
Software Engineer
University of Washington
mitchellsundt@gmail.com
