### ISSUE TITLE
New questionnaire not uploading anymore. URGENT, data collection going on now.

### ISSUE THREAD

**Issue by rctendline** [opendatakit/opendatakit#1215]
ODK aggregate seems to be past its daily quota, even after we increase the budget. Everything is working in terms of viewing and exporting submissions on existing forms, but we are unable  to add any new forms. We have tried deleting old forms to free up memory, but this doesn't seem to solve the problem. Data collection is going on right now, we can't reach an answer. Please we appreciate help.

**Comment by mitchellsundt** [comment]
Go to your Form Management page. 

Is "Accept Submissions" checked? 

If this is unchecked, then ODK Collect will not be able to submit filled-in forms to your server.

**Comment by mitchellsundt** [comment]
You should ask operational questions on the opendatakit@ list.

**Comment by mitchellsundt** [comment]
Closing this, as it is best to discuss on the opendatakit@ list.
