### ISSUE TITLE
Default field value to last submitted form

### ISSUE THREAD

**Issue by geotheory** [opendatakit/opendatakit#1216]
I think I'm right that ODK doesn't currently have functionality to specify that a field's default value should be inherited from the last form submitted?  If so it strikes me as a very useful feature to add to handle fields such as batch/event IDs that stay the same for a while until the next group.  If you have e.g. hundreds of forms to submit it saves a lot of time and reduces risk of typo errors.  Is this something you'd consider building in?

**Comment by mitchellsundt** [comment]
No. This requires a lot of information about the meaning of a field. And raises questions with the security of encrypted forms if some or all of their fields might be cached for use as defaults in a subsequent form.

External applications can populate this information for your specific use case, or barcodes scanned from paper-based documentation can be used to simplify the data-entry of this information.
