### ISSUE TITLE
Incomplete switch over to "default" app name

### ISSUE THREAD

**Issue by linl33** [opendatakit/opendatakit#1217]
**Description**
Survey created a "survey" directory under the "opendatakit" directory. 

**Expected behavior**
Survey should store files under "default".

**Comment by jbeorse** [comment]
I have not been able to reproduce this error on my end. Can you confirm you have the latest code, as it exists in the "demo" branch? Do you have repro steps?

**Comment by mitchellsundt** [comment]
This is fixed in:

 https://github.com/opendatakit/services/commit/580c102100423845acea4b5ea93f683a753c8cf9

(services is where this was happening).
