### ISSUE TITLE
Incorrect element name

### ISSUE THREAD

**Issue by linl33** [opendatakit/opendatakit#1218]
**Description**
Under columns in table preferences, both the "element key" field and "element name" field show the element key. 

![image](https://cloud.githubusercontent.com/assets/8204095/14401188/27c53752-fdbd-11e5-8058-6e2837ad498f.png)

**Comment by mitchellsundt** [comment]
This is actually expected. The name diverges when you are dealing with complex user-defined data types or things like image attachments or geopoints

**Comment by linl33** [comment]
Fixed
