### ISSUE TITLE
ODK Aggregate Doesn't play video files in Google Chrome and Safari

### ISSUE THREAD

**Issue by julesverne1** [opendatakit/opendatakit#1221]
Hello,

ODK Aggregate only play the video files via Firefox. It would be amazing to solve this issue as (in my case) the map viewers might use different platforms than the Firefox.

Thank you for this amazing tool.

**Comment by mitchellsundt** [comment]
This may be a lack of codecs or a difference in the treatment of HTML tags that we use to provide the video links across the various browsers.

**Comment by julesverne1** [comment]
Any solution advice?

**Comment by mitchellsundt** [comment]
sorry, no. This is a low priority for us at this time.

What is the file type (extension) of your video files?

Different browsers only support some video formats.

https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats

In terms of file extensions, Chromium (Chrome browser) recognizes the
following (defined in src/net/base/mime_util.cc
<https://chromium.googlesource.com/chromium/src/+/master/net/base/mime_util.cc>
):
mp4, m4v, m4a, mp3, ogv, ogm, ogg, oga, webm, wav
.
You might be able to work around this by changing the default file type
produced by your device's camera (e.g., mp4 vs 3gpp or wav).


On Tue, May 17, 2016 at 2:48 AM, julesverne1 <notifications@github.com>
wrote:

> Any solution advice?
>
> On Mon, May 16, 2016 at 9:38 PM, Mitch Sundt <notifications@github.com>
> wrote:
>
> > This may be a lack of codecs or a difference in the treatment of HTML
> tags
> > that we use to provide the video links across the various browsers.
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/opendatakit/opendatakit/issues/1221#issuecomment-219524538
> >
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/opendatakit/opendatakit/issues/1221#issuecomment-219670535>
>



-- 
Mitch Sundt
Software Engineer
University of Washington
mitchellsundt@gmail.com

**Comment by julesverne1** [comment]
My file type is mp4. (and this doesnt explain why one out of seven video is
playing but not the rest. It's really weird)

And in my mapping project I will ask many different people (with different
skills and command on Android phone) to submit videos so unfortunately I
cant ask everyone to change the file types.

This is unfortunate for me but thank you for your interest and effort for
trying to come up with solutions.

Have a great day.

**Comment by mitchellsundt** [comment]
Thanks. mp4 is already supported in the submission flow. I was hoping your
device was using a newer encoding format that we didn't yet explicitly
support.


On Mon, May 23, 2016 at 4:11 AM, julesverne1 <notifications@github.com>
wrote:

> My file type is mp4. (and this doesnt explain why one out of seven video is
> playing but not the rest. It's really weird)
>
> And in my mapping project I will ask many different people (with different
> skills and command on Android phone) to submit videos so unfortunately I
> cant ask everyone to change the file types.
>
> This is unfortunate for me but thank you for your interest and effort for
> trying to come up with solutions.
>
> Have a great day.
>
>
> On Tue, May 17, 2016 at 6:41 PM, Mitch Sundt <notifications@github.com>
> wrote:
>
> > sorry, no. This is a low priority for us at this time.
> >
> > What is the file type (extension) of your video files?
> >
> > Different browsers only support some video formats.
> >
> >
> https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats
> >
> > In terms of file extensions, Chromium (Chrome browser) recognizes the
> > following (defined in src/net/base/mime_util.cc
> > <
> >
> https://chromium.googlesource.com/chromium/src/+/master/net/base/mime_util.cc
> > >
> > ):
> > mp4, m4v, m4a, mp3, ogv, ogm, ogg, oga, webm, wav
> > .
> > You might be able to work around this by changing the default file type
> > produced by your device's camera (e.g., mp4 vs 3gpp or wav).
> >
> >
> > On Tue, May 17, 2016 at 2:48 AM, julesverne1 <notifications@github.com>
> > wrote:
> >
> > > Any solution advice?
> > >
> > > On Mon, May 16, 2016 at 9:38 PM, Mitch Sundt <notifications@github.com
> >
> > > wrote:
> > >
> > > > This may be a lack of codecs or a difference in the treatment of HTML
> > > tags
> > > > that we use to provide the video links across the various browsers.
> > > >
> > > > —
> > > > You are receiving this because you authored the thread.
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/opendatakit/opendatakit/issues/1221#issuecomment-219524538
> > > >
> > > >
> > >
> > > —
> > > You are receiving this because you commented.
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/opendatakit/opendatakit/issues/1221#issuecomment-219670535
> > >
> > >
> >
> >
> >
> > --
> > Mitch Sundt
> > Software Engineer
> > University of Washington
> > mitchellsundt@gmail.com
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/opendatakit/opendatakit/issues/1221#issuecomment-219778163
> >
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/opendatakit/opendatakit/issues/1221#issuecomment-220951926>
>



-- 
Mitch Sundt
Software Engineer
University of Washington
mitchellsundt@gmail.com

**Comment by jbeorse** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jeffisveryhungry@gmail.com
    Domain beorse.net has exceeded the max emails per hour (275/250 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:30846)
	by hp159.hostpapa.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-c877-jeff=beorse.net@sgmail.github.com>)
	id 1dgMCh-000eak-IB
	for jeff@beorse.net; Fri, 11 Aug 2017 22:31:07 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=X7KL7xOOjzMkvEj1t16aizUXwdk=; b=VgOcwbJDJS9FHUuO
	udxTzFc+CPRkfQk2B5UEhS0wZtwIjQDn2JKzE7bmvOxomwTAMhFZr21dM/elv7vx
	woh5ARfU5n2DMX4nUgxvBCRBhSkVTihIdBjMVyfhWXesbjq6HaIQmix/Xngvh20C
	Ry/CCW60u+VCulnFX+AYzv9TpVw=
Received: by filter1144p1mdw1.sendgrid.net with SMTP id filter1144p1mdw1-24900-598E6843-3B
        2017-08-12 02:30:27.873348526 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0038p1mdw1.sendgrid.net (SG) with ESMTP id fOqM9NpRSjS5YFJ3px-_4w
	for <Jeff@Beorse.net>; Sat, 12 Aug 2017 02:30:27.753 +0000 (UTC)
Date: Sat, 12 Aug 2017 02:30:27 +0000 (UTC)
