### ISSUE TITLE
Unknown geopoint <hint>-Element in XForm from XLSForm

### ISSUE THREAD

**Issue by mkne** [opendatakit/opendatakit#1222]
The following line was found in a XForm file produced by http://opendatakit.org/xiframe/ from a xlsx file: <hint>GPS coordinates can only be collected when outside.</hint>
In the xlsx file the hint column is empty. After looking into the ODK Collect sources and translating all strings to German this is the last remaining English in my survey. Even a completely new xlsx file with only a geopoint has this hint after conversion.

**Comment by chrislrobert** [comment]
That's the default hint. Poor form that it's in English. But you can override it by including non-blank hints in your XLSForm.

**Comment by mkne** [comment]
But why is there a hint at all if the hint column is empty. I've attached my simple test xlsx file which I used to verify the error. So would the user (who is not able to read xml) have to add a blank in the hint column if he doesn't want a hint. I think this would be a very poor solution. Because the blank would probably result in a blank line which might not be the desired layout. But maybe there is something else wrong in the settings of the XLSForm.
[Lageplan.xlsx](https://github.com/opendatakit/opendatakit/files/264690/Lageplan.xlsx)

**Comment by chrislrobert** [comment]
The pyxform converter adds this default hint for geopoint fields whenever it doesn't see some other hint already in the XLSForm. Poor solution? Yes. I'm just telling you how it is, and how to work around it. I'm not saying that it wasn't a terrible idea, and I'm not saying that somebody shouldn't fix it some day (with apologies to everybody who might possibly rely on it).

**Comment by mkne** [comment]
Thank you for your clarification. I didn't know that the converter is also open source. Maybe this issue helps some future users who also stumble over this problem or I find the time to fix it.

**Comment by mberg** [comment]
Marc,

Feel free to make a pull-request with rationale for the change or create an
issue with the suggested change.

https://github.com/XLSForm/pyxform

Thanks,

Matt

**Comment by yanokwa** [comment]
Fixed at https://github.com/XLSForm/pyxform/pull/67.
