### ISSUE TITLE
Markdown TextUtils bug

### ISSUE THREAD

**Issue by mitchellsundt** [opendatakit/opendatakit#1224]
*Migrated to opendatakit/collect#196 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

From Google Play Store:

java.lang.ArrayIndexOutOfBoundsException: length=4; index=10
	at java.util.regex.Matcher.group(Matcher.java:358)
	at java.util.regex.Matcher.appendEvaluated(Matcher.java:138)
	at java.util.regex.Matcher.appendReplacement(Matcher.java:111)
	at org.odk.collect.android.utilities.TextUtils.markdownToHtml(TextUtils.java:49)
	at org.odk.collect.android.utilities.TextUtils.textToHtml(TextUtils.java:108)
	at org.odk.collect.android.views.HierarchyElementView.setPrimaryText(HierarchyElementView.java:75)
...

This error is due to the inappropriate use of this idiom in TextUtils.markdownToHtml(html):

Xmatcher.appendReplacement(output, createXReplacement(Xmatcher));

The problem is that appendReplacement will examine the string returned by createXReplacement() to find substitution actions like ${1} and attempt to replace those with elements retrieved from the Xmatcher.  See https://docs.oracle.com/javase/7/docs/api/java/util/regex/Matcher.html#appendReplacement(java.lang.StringBuffer,%20java.lang.String)

Either the code needs to be changed so that the return content is a proper replacement substitution string or this code needs to be reworked to not use the appendReplacement() method.

**Comment by yanokwa** [comment]
Not sure I get it. Any chance you can whip up a sample form that shows the issue?

**Comment by mitchellsundt** [comment]
Here's an example.  The replacement strings are parsed and interpreted according to the rules described in the link above.

[markdown.xml.txt](https://github.com/opendatakit/opendatakit/files/275023/markdown.xml.txt)
