### ISSUE TITLE
Form ID Not 

### ISSUE THREAD

**Issue by ircslc** [opendatakit/opendatakit#1230]
I receive this error when trying to upload an updated version of a form:

Error: Form did not specify a Form ID. For information on Form ID please check the Open Data Kit FAQ

This is a copy of what I have on my "settings" tab:
[settings.xlsx](https://github.com/opendatakit/opendatakit/files/321446/settings.xlsx)

I have not encountered this problem before, but duplicated it many times today.  I tried renaming the form id, that didn't work.  I tried deleting the settings tab, that worked to upload one form, but if I try to make any changes it again tells me I did not specify a form ID.

I create the form in Excel then convert to xls through XLSForm Offline by Nafundi 1.4.0

I upload to ODK Aggregate.

Please let me know if you need any other information, or are able to guide me to a solution.

Thank you!!!

**Comment by mitchellsundt** [comment]
As always, when you have this problem, go back to the example XLSX file and
see what you changed that caused the problem. The form id and XLSX filename
that you convert should not contain any special characters, accents or
spaces.


On Fri, Jun 17, 2016 at 5:08 PM, ircslc <notifications@github.com> wrote:

> I receive this error when trying to upload an updated version of a form:
>
> Error: Form did not specify a Form ID. For information on Form ID please
> check the Open Data Kit FAQ
>
> This is a copy of what I have on my "settings" tab:
> settings.xlsx
> <https://github.com/opendatakit/opendatakit/files/321446/settings.xlsx>
>
> I have not encountered this problem before, but duplicated it many times
> today. I tried renaming the form id, that didn't work. I tried deleting the
> settings tab, that worked to upload one form, but if I try to make any
> changes it again tells me I did not specify a form ID.
>
> I create the form in Excel then convert to xls through XLSForm Offline by
> Nafundi 1.4.0
>
> I upload to ODK Aggregate.
>
> Please let me know if you need any other information, or are able to guide
> me to a solution.
>
> Thank you!!!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/opendatakit/opendatakit/issues/1230>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/ACLO0wisivMyiDXD8-z2UBwJLSCZNstuks5qMzcOgaJpZM4I40jj>
> .
>



-- 
Mitch Sundt
Software Engineer
University of Washington
mitchellsundt@gmail.com
