### ISSUE TITLE
Can't 'reset app server' - ODK 2.0 rev204

### ISSUE THREAD

**Issue by chegeiser** [opendatakit/opendatakit#1231]
When I try to reset the app server it appears to be syncing fine - and then errors out. The error on the android device screen shows:
"ODK Sycn default Error. Protocol Error. Please verify that the server and device are compatible."

I've had the same result using the main Aggregate admin account login details and a Google account that has Synchronize Tables, Administer Tables and Site Administrator rights. I've also tried on a Nexus 4 and a Samsung Galaxy Tab S. I get the same error on both.

My Aggregate is v1.4.9 hosted on Amazon AWS as a T1.micro instance - I upgraded to T1.small instance to see if there was a hangup due to speed/processing power. This did not help.

Thank you for any assistance!
Che

**Comment by clarlars** [comment]
Hi Che,

If you could capture a log using adb logcat when you get this error, that
would help in troubleshooting the issue.  Directions on how to do this can
be found at
https://github.com/opendatakit/opendatakit/wiki/Collect-Troubleshooting.
What version of the Android OS is on your devices?

Thanks,
Clarice

**Comment by bvnbbn** [comment]
hey can you please help me and tell me how to import collect  source code
from github I  have read all the instructions and tried to iumport it but I
am getting this error

Error:(12, 0) CreateProcess error=2, The system cannot find the file
specified
<a href="openFile:C:\Users\Vikas\ODK\collect\collect_app\build.gradle">Open
File</a>

**Comment by mitchellsundt** [comment]
I believe this is the known issue: if you are resetting the app server, you
need to remove the Synchronize Tables permission from the anonymousUser
while you do that. Otherwise you will get a Protocol error (and, in
v1.4.10, you will get an Authorization failure).


On Mon, Jun 20, 2016 at 5:58 PM, clarlars <notifications@github.com> wrote:

> Hi Che,
>
> If you could capture a log using adb logcat when you get this error, that
> would help in troubleshooting the issue. Directions on how to do this can
> be found at
> https://github.com/opendatakit/opendatakit/wiki/Collect-Troubleshooting.
> What version of the Android OS is on your devices?
>
> Thanks,
> Clarice
>
>
> On Mon, Jun 20, 2016 at 4:12 PM, chegeiser <notifications@github.com>
> wrote:
>
> > When I try to reset the app server it appears to be syncing fine - and
> > then errors out. The error on the android device screen shows:
> > "ODK Sycn default Error. Protocol Error. Please verify that the server
> and
> > device are compatible."
> >
> > I've had the same result using the main Aggregate admin account login
> > details and a Google account that has Synchronize Tables, Administer
> Tables
> > and Site Administrator rights. I've also tried on a Nexus 4 and a Samsung
> > Galaxy Tab S. I get the same error on both.
> >
> > My Aggregate is v1.4.9 hosted on Amazon AWS as a T1.micro instance - I
> > upgraded to T1.small instance to see if there was a hangup due to
> > speed/processing power. This did not help.
> >
> > Thank you for any assistance!
> > Che
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/opendatakit/opendatakit/issues/1231>, or mute the
> > thread
> > <
> https://github.com/notifications/unsubscribe/AHsHMGlH043CMKaaYcd-Dvz1lSO00a9zks5qNx5cgaJpZM4I6OA-
> >
> > .
>
> >
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/opendatakit/opendatakit/issues/1231#issuecomment-227312804>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACLO06iSLG5nsTnH0w3yMJjOlGy7eY1vks5qNzcigaJpZM4I6OA->
> .
>



-- 
Mitch Sundt
Software Engineer
University of Washington
mitchellsundt@gmail.com

**Comment by jbeorse** [comment]
Fixed or not an issue as of RC2 or earlier
