### ISSUE TITLE
Plot visit survey date picker issue

### ISSUE THREAD

**Issue by mnevalsky** [opendatakit/opendatakit#1242]
If you try to advance past the date picker page without selecting a date, the constraint message appears but then it does not allow you to choose the date unless you back out and return to the page again.

**Comment by yanokwa** [comment]
Hi @mnevalsky. Are you using ODK Survey or ODK Collect? If it's ODK Collect, please file it at https://github.com/opendatakit/collect/issues/new. Thanks!

**Comment by jbeorse** [comment]
Fixed or not an issue as of RC2 or earlier
