### ISSUE TITLE
Automating the data-corruption clean-up

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/opendatakit#1253]
From Mitch...

"The goal should be to make altering of the data on the server an explicit user action. This could be via a new button on the Form Management / Submission Admin sub-tab (e.g., "Repair Submission") that prompted for the instanceID of the problematic row.

But, implementing that action is tricky because of the many different ways that failures can occur, with duplicates or omissions of records in any of the form's tables leading to data corruption.  While it is somewhat straightforward in forms without repeat groups, this gets particularly complicated when there are repeat groups because those can be arbitrarily deeply nested.

Given how difficult it has been to generate unique column names in the face of large deeply-nested forms (there are still forms for which this fails), I, personally, would not trust any code written to automatically repair a submission; developing tests to verify the correct handling of all data corruption failure cases would be similarly impossible.  

Perhaps a first step would be for the "Repair Submission" action to generate a report containing the GQL or SQL statements that users could cut-and-paste to investigate the errors, confirm the recommendations, and effect the deletions themselves.

4 hr: The plumbing between the GWT-based UI (new button, new pop-up dialog) and a servlet for this, and the changes to the web.xml and security configuration to show everything is about 4 hours (an example would be the upload-permissions-csv feature in 1.4.12; note: that is spread across several check-ins).

3 days: I would push the GQL / SQL syntax construction down into the persistence engine implementations. This is already what is done internally with queries in the PostgreSQL / MySQL case, so you'd just need to grab the query string without executing the query. For Google, you would need to add that functionality (since it is all API-based).  Probably about 2-3 days for this to understand the layers, add the new APIs and write the Google GQL syntax writer.

3-10 days: Writing the servlet that would lay out HTML content with details on a specific instance ID within a table. It depends upon how fancy you want to make the page and making sure you handle all the shadow, select-multiple, repeat group, and attachment tables correctly."

**Comment by jbeorse** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jeffisveryhungry@gmail.com
    Domain beorse.net has exceeded the max emails per hour (281/250 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:37178 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by hp159.hostpapa.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89)
	(envelope-from <noreply@github.com>)
	id 1dgMCp-000edv-1z
	for Jeff@Beorse.net; Fri, 11 Aug 2017 22:31:15 -0400
Date: Fri, 11 Aug 2017 19:30:34 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1502505034;
	bh=sIJz4gKGl+YII5J8LCUpx6ED+StPcJ4QTkqyztOZZrU=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=GtIE2dC/0ApC8kLERqzsOHss3m/pIYBSgcGrDFb+ec6GSycPWorl/exIV2hVfNeSH
	 hfYRCLxkGa8RtI2qADrvBumtnPqcYjzd6pw20+1o2FDi7aYpu5SNMnH6wkNonbI3V4
	 P3T6Z0YofayOlGzvw1w6PajlunbOQu/+uJrhfkUE=
