### ISSUE TITLE
postgres9 doesn't inherit permission

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/opendatakit#1255]
"We are using postgres9 and aggregate 1.4.7. We find ourselves having to re-create DB permissions for the new tables every time a new version is uploaded and new tables are created by uploading a form definition.  If we create a table manually it inherits the default permissions fine, but not for those created by form definition upload."

**Comment by jbeorse** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jeffisveryhungry@gmail.com
    Domain beorse.net has exceeded the max emails per hour (283/250 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:39591 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by hp159.hostpapa.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89)
	(envelope-from <noreply@github.com>)
	id 1dgMCp-000eeA-7c
	for Jeff@Beorse.net; Fri, 11 Aug 2017 22:31:15 -0400
Date: Fri, 11 Aug 2017 19:30:35 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1502505035;
	bh=MQd2Bfpa9etdHBV/rQADjIOcQN+eB+iLskM/VlYCd9I=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=F67okXC9vNJUYI1T7/I2S8WJ0vQAGMVExbWT8qG6UxFHSmY//Qbw69h4ffBgVjXoE
	 dSJLgGaDGpJo7FekN+/37DscAfLmXI7jOYyrktCIsdLAE5VKUKuss07k/4QuA55lXj
	 APtKJVMOMmQJ5meJvqh0ki6/l2AVcgLFQLFD6/+c=
