### ISSUE TITLE
database_hostname and database_port aren't set in jdbc.properties

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/opendatakit#1262]
If you run the Linux 64 bit Aggregate 1.4.11 installer in command line mode, the variables you set in database_hostname and database_port, don't get passed through to WEB-INF/lib/ODKAggregate-settings.jar/jdbc.properties.

Expect: `jdbc.url=jdbc:mysql://12.34.56.89:3306/odk_prod?autoDeserialize=true`
Actual: `jdbc.url=jdbc:mysql:///odk_prod?autoDeserialize=true`

**Comment by mitchellsundt** [comment]
There is also an installer variable:  

  database_host_port

That is ${database_hostname}:${database_port}

This needs to be set for command line usage, as it is initialized via a postShowPageActionList action (this is the only variable set in this way).  So via CLI, it wouldn't be initialized.

This is NOT fixed in v1.4.13.

**Comment by jbeorse** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jeffisveryhungry@gmail.com
    Domain beorse.net has exceeded the max emails per hour (288/250 (115%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:42591 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by hp159.hostpapa.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89)
	(envelope-from <noreply@github.com>)
	id 1dgMDU-000eyA-C1
	for Jeff@Beorse.net; Fri, 11 Aug 2017 22:31:56 -0400
Date: Fri, 11 Aug 2017 19:31:16 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1502505076;
	bh=6UCZJjIQWl4bc9kbVLl6l0Up/fZ0Lt1VRUOkKEcQ2Tk=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=vNfKjXNk6Be/eefJbj2wNrm+T5iX9+X4AckS41Vy3WpZsml/VwiQ3qNFArkobeybl
	 f483H8oTK5Zz5Yy8ufojLg0s/MYQkyqeggSJkfX+1joEkfajtKKVwv/VbT+JwKvcd7
	 0Zo69FPX7+2RIxIIEN2JxVYoEiSx0QTxnp2JbbbA=
