### ISSUE TITLE
Option when completing form to reopen same blank new form

### ISSUE THREAD

**Issue by geotheory** [opendatakit/opendatakit#1263]
Title pretty much says it I think. When you're repetitively inputting a lot of records the process of going back to forms menu is just an extra unnecessary step.  Would be good if an option could be added at end of form to reopen a fresh blank version of the same form again.

**Comment by yanokwa** [comment]
Hi @geotheory! What ODK tool are you using?

**Comment by geotheory** [comment]
@yanokwa Sorry. ODK Collect.

**Comment by yanokwa** [comment]
In that case, please refile at https://github.com/opendatakit/collect/issues!
