### ISSUE TITLE
Data of a repeat group inside a repeat group does not export to Fusion Table

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/opendatakit#1264]
If you have a repeat group B inside a repeat group A, and you submit that data to Aggregate, the submission works fine. If you publish that data to Fusion Tables, the tables are created, but the sub repeat group (B)'s tables will be empty.

To replicate this issue, I used this [fusion-test.xlsx] form (https://github.com/opendatakit/opendatakit/files/675712/fusion-test.xlsx) to generate a sample submission. 

```
<?xml version='1.0' ?>
<fusion-test id="fusion-test">
	<repeat_a>
		<text_a>a1</text_a>
		<repeat_b>
			<text_b>a1b1</text_b>
		</repeat_b>
		<repeat_b>
			<text_b>a1b2</text_b>
		</repeat_b>
		<repeat_b>
			<text_b>a1b3</text_b>
		</repeat_b>
	</repeat_a>
	<repeat_a>
		<text_a>a2</text_a>
		<repeat_b>
			<text_b>a2b1</text_b>
		</repeat_b>
		<repeat_b>
			<text_b>a2b2</text_b>
		</repeat_b>
		<repeat_b>
			<text_b>a2b3</text_b>
		</repeat_b>
		<repeat_b>
			<text_b>a2b4</text_b>
		</repeat_b>
	</repeat_a>
	<repeat_a>
		<text_a>a3</text_a>
	</repeat_a>
	<meta>
		<instanceID>uuid:43a8623f-1a00-4174-8bb2-712d9e048b43</instanceID>
	</meta>
</fusion-test>
```

When this submission is sent to Aggregate, the right things happen.

*Aggregate, Repeat A*
![ag_a](https://cloud.githubusercontent.com/assets/32369/21524407/d22034c2-cce3-11e6-838e-7202295d7b72.png)

*Aggregate, Repeat A1B*
![ag_a1_b](https://cloud.githubusercontent.com/assets/32369/21524406/d2204d68-cce3-11e6-803d-fe4679653e07.png)

*Aggregate, Repeat A2B*
![ag_a2_b](https://cloud.githubusercontent.com/assets/32369/21524557/f4344124-cce4-11e6-912a-cf9a1dda78d3.png)

When this submission is sent to Fusion Tables, the sub repeat (B) shows up as empty.

*Fusion Table, Repeat A*
![ft_a](https://cloud.githubusercontent.com/assets/32369/21524408/d2206500-cce3-11e6-9c79-bfa3573161c0.png)

*Fusion Table, Repeat B*
![ft_b](https://cloud.githubusercontent.com/assets/32369/21524405/d220199c-cce3-11e6-84ed-2898a6506acf.png)

**Comment by mitchellsundt** [comment]
This was an intentional limitation of repeat-group support in the publishers. I think Waylon coded these in a few days; constructing the top-level view was becoming insanely difficult.

Repeat group support is also broken in significant ways in Sheets.

**Comment by yanokwa** [comment]
@wbrunette What approach would you take to fix this?

**Comment by jbeorse** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jeffisveryhungry@gmail.com
    Domain beorse.net has exceeded the max emails per hour (291/250 (116%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:31113)
	by hp159.hostpapa.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-c877-jeff=beorse.net@sgmail.github.com>)
	id 1dgMDY-000f01-5Y
	for jeff@beorse.net; Fri, 11 Aug 2017 22:32:00 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=O7kbkX+7iIP3p1T4UEXViq4LULc=; b=wBHR/aV5CiqbKuUU
	E/8WuefdjJxWQS8Y7mEarey+HoA9YnQ5Rj5Oc+p/7zdRYMuDcRBOxbddPNgzRKzW
	5pbmMlA5LJ/rBTdpC64wWHC2fqsVAymdVg2PFdBA2W29fg/9khvd07M7c6QILcr8
	Y/2+p84M9aM1eG0oBwm+Ysi/MaA=
Received: by filter0536p1mdw1.sendgrid.net with SMTP id filter0536p1mdw1-14295-598E6878-4
        2017-08-12 02:31:20.044609695 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0025p1mdw1.sendgrid.net (SG) with ESMTP id 58giNo_aQlSwifhnqZQfWw
	for <Jeff@Beorse.net>; Sat, 12 Aug 2017 02:31:19.935 +0000 (UTC)
Date: Sat, 12 Aug 2017 02:31:20 +0000 (UTC)
