### ISSUE TITLE
CSV Exports Fail

### ISSUE THREAD

**Issue by TimboSid** [opendatakit/opendatakit#1268]
Hello, I exported my data sets on Jan 30, and then we got more submissions from our health workers and I"m trying to export again, but every export attempt fails. I have no idea why. 

After multiple failed attempt to download I exceed my quota and I'm locked out.

Any suggestions?

Here are screenshots: 
![screen shot 2017-02-02 at 10 37 56 am](https://cloud.githubusercontent.com/assets/18620588/22546153/c418305c-e933-11e6-8a96-23cc4f1ad471.png)
![screen shot 2017-02-02 at 10 47 31 am](https://cloud.githubusercontent.com/assets/18620588/22561285/71a933fc-e96f-11e6-86b2-179fae1d1ccb.png)

**Comment by TimboSid** [comment]
So bulk exporting resulted in failed attempts. Then I decided to try exporting with filters, to break the bulk up into 7 chunks. And all 7 groups exported without an issue. So I was able to get all my data, but not in one bulk download.

Any idea what that's about?

**Comment by TimboSid** [comment]
Update: actually one of my data sets (filtered by variable) is somehow corrupted, and I can't export it. Anyone out there?

**Comment by yanokwa** [comment]
What version of Aggregate are you using?

The error message suggests some data corruption. Try the steps at https://github.com/opendatakit/opendatakit/wiki/Aggregate-AppEngine-Troubleshooting. Upgrade to Aggregate 1.4.13 to reduce the chance of corruption.

Independent on that, very large datasets sometimes don't work on Aggregate running on App Engine. Use Briefcase and see if that works better.

**Comment by jbeorse** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jeffisveryhungry@gmail.com
    Domain beorse.net has exceeded the max emails per hour (301/250 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:42171 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by hp159.hostpapa.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89)
	(envelope-from <noreply@github.com>)
	id 1dgMDj-000f4R-5Y
	for Jeff@Beorse.net; Fri, 11 Aug 2017 22:32:11 -0400
Date: Fri, 11 Aug 2017 19:31:31 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1502505091;
	bh=M2lP11rcN7dN8s3YrCKU4o5Bm7Ec2DkkH10joR0WfVE=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=DvUll9QoRITLyT1CNVEjEtuPfFglQ+QxataI2t/I4rZuaeCMOHAafp7vOHWaRcf44
	 vHa7bqSaHJ4zg9U21Mm1riEzt8l2RI78s8woBF5Ge7tJvejwkxUErGM6F3T1KB2FWF
	 v2x5LlnHOvHvFxrbIdHqSM+FDgSnefjOkfqXOcvA=
