### ISSUE TITLE
In Web Views, back button should navigate back through the Web View history instead of exiting it

### ISSUE THREAD

**Issue by magdalenacassel** [opendatakit/opendatakit#1269]
####Tool: ODK Tables

We are taking advantage of the ability to add custom html and JavaScript to ODK Tables.  We have some single-page navigation in our custom page.  Right now, when we press the back button, the Web View closes and the user's position is lost.  We need to be able to respond to the event produced by the back button and suppress the native handling.  This needs to be enabled from the Java side.

The expected behavior from a user's point of view would be to navigate back through the Web View's history until there is no more, than exit the Web View after that.

Something like:
``` java
@Override
public void onBackPressed() {
    if (webView.canGoBack()) {
        webView.goBack();
    } else {
        super.onBackPressed();
    }
}
```

**Comment by jbeorse** [comment]
You can do this with a launchHtml call. When you hit back you will go to the caller of launchHtml. With this you can construct whatever back stack you like
