### ISSUE TITLE
Aggregate 1.4.13 fails to start with PostgreSQL 9.3

### ISSUE THREAD

**Issue by zwets** [opendatakit/opendatakit#1270]
When installing Aggregate 1.4.13 with a PostgreSQL 9.3 backend, the application fails to initialise. With PostgreSQL 9.5 it works fine.

#### Configuration

WAR deployment on Tomcat 8.5.11 on Ubuntu 14.04 LTS with default JRE (OpenJDK 7u121) and default PostgreSQL (9.3). Freshly created database using `create_db_and_user.sql`.

#### Problem description

The application fails to start. SQL exceptions are logged in `catalina.out`. The innermost exception thrown is `java.sql.SQLException: validationQuery didn't return a row`.

#### Diagnosis

The validation query referenced in the root exception is set in the `validationQuery` property on the `dataSource` bean in `WEB-INF/lib/ODKAggregate-settings.jar:odk-settings.xml` to be `select schema_name from information_schema.schemata limit 1`.

When executing that query as the odk database user against its database on PostgreSQL 9.3, the query returns 0 records. On PostgreSQL 9.5 it returns 1 record.

The issue seems specific to PostgreSQL 9.3, not to the odk database user. Any regular database user executing that query gets an empty result on 9.3, and 1 record on 9.5.  The `postgres` superuser does get the expected 1 record on both. 

AFAIK my 9.3 and 9.5 database instances are configured identically. Maybe there was a default permissions change between PostgreSQL versions?

#### Workaround

My (quick &  dirty) workaround was to replace the validationQuery by `select 1`:

```bash
jar xf ODKAggregate.war WEB-INF/lib/ODKAggregate-settings.jar
jar xf WEB-INF/lib/ODKAggregate-settings.jar odk-settings.xml
sed -i -e 's/schema_name from information_schema.schemata limit//' odk-settings.xml
jar uf WEB-INF/lib/ODKAggregate-settings.jar odk-settings.xml
jar uf ODKAggregate.war WEB-INF/lib/ODKAggregate-settings.jar
```

**Comment by mitchellsundt** [comment]
I've updated the Aggregate 1.4.13 upgrade steps to direct users to upgrade to PostgreSQL 9.4 or newer. This appears to be an issue with permissions required to access to the information_schema content. That appears to be resolved in 9.4 and higher.

**Comment by zwets** [comment]
Thanks @mitchellsundt but wouldn't it be better to change the validation query so as to make this work irrespective of PostgreSQL version? PostgreSQL 9.3 will be around [for another year and a half](https://www.postgresql.org/support/versioning/), and in many places won't/can't be upgraded to 9.4.

In applications that don't create their own tables, the validation query usually checks that some core table is found in the database, so that the application can "fail fast" when connected wrongly. In our case, where there may or may not be ODK tables yet in the database, the purpose of the validation query is really only to check that there is a PostgreSQL at the other end of the connection. For this, a `SELECT 1` would suffice. 

Using `SELECT schema_name FROM information_schema.schemata WHERE schema_name = 'my-expected-schema-name'` would add some value to the validation. However `SELECT schema_name FROM information_schema.schemata LIMIT 1` adds close to none relative to `SELECT 1`.

**Comment by mitchellsundt** [comment]
Yes, the validation query could be changed BUT, within ODK Aggregate, we ***MUST***be able to run select statements against the information_schema. If that fails, then ODK Aggregate will never function correctly.  So in this case, having a validation query that confirms you can access the information_schema is actually beneficial, as it catches this failure very early.

e.g., 

https://github.com/opendatakit/aggregate/blob/master/src/main/java/org/opendatakit/common/persistence/engine/pgres/DatastoreImpl.java#L180

The remedy is to add a grant to that schema when running against older versions. 

e.g., something like the following as part of the create_db_and_user.sql content:

grant all privileges on schema "information_schema" to "your_odk__user";

Or perhaps just "usage" ?  I am unclear whether usage would be sufficient for running select queries against the tables within the schema.

**Comment by mitchellsundt** [comment]
This is a puzzling failure that seems to be an issue with how 9.3 does grants, as everything was working on 9.1.x, and then everything is working on 9.4 (the version I used when updating everything to use JDBC 4 and Tomcat 8).

**Comment by zwets** [comment]
`GRANT` either `USAGE` or `ALL` on `information_schema` did not help so I looked a bit deeper. I've spotted the issue, and think I've got the clean solution.

Strangely, `SELECT * FROM information_schema.columns` works fine, which probably explains why my ODK instance is actually working on 9.3 ... until it breaks on another possible `information_schema.*` table permissions issue :-/

So what is the issue with `information_schema.schemata`? Looking at its definition (using `\d+  information_schema.schemata` in psql) gave a clue. It is defined as a view, with one significant difference between 9.3 and 9.5:

```sql
SELECT ... FROM pg_namespace n, pg_authid u ...
-- 9.3
WHERE n.nspowner = u.oid AND pg_has_role(n.nspowner, 'USAGE'::text);
-- 9.5
WHERE n.nspowner = u.oid AND (pg_has_role(n.nspowner, 'USAGE'::text)
                              OR has_schema_privilege(n.oid, 'CREATE, USAGE'::text));
```

Note that `n` aliases `pg_namespace` which is the 'real' table of schemata, and `u` aliases `pg_authid`, the table of user accounts (needed only to display the schema owner names).

The `WHERE` clause filters the rows the user gets to see. The check `pg_has_role` checks that the current user has the `USAGE` permission for the role `n.nspowner`. In other words, can the ODK user assume the role of the schema owner? Since the schema owner of the _ODK schema_ is `postgres` this is false.

On 9.5, things work out because of the disjunct: the ODK user _does_ have `USAGE` (and `CREATE`) privilege for the ODK schema (even if `postgres` is the schema owner), as the schema sits in its own ODK database, for which it is granted ALL.

The obvious solution then is to make the ODK user the owner of its own schema. 

In `create_db_and_user.sql`, add the statement `alter schema "odk_schema" owner to "odk_user"`(in fact, this could probably replace the current `grant all privileges on schema "odk_schema" to "odk_user").

**Comment by mitchellsundt** [comment]
Can you confirm that the additional grant on information_schema is not required?

I will add the alter-owner to the script. Update will be in the next ODK Aggregate release (no ETA).

**Comment by zwets** [comment]
I have just tested it on 9.3 with a freshly created user and database, and no grants (either on `information_schema` or the `odk_schema`) are needed:

```sql
create database testdb;
create user testuser with unencrypted password 'secret';
alter database testdb owner to testuser;
\c testdb
You are now connected to database "testdb" as user "postgres".
create schema testschema;
alter schema testschema owner to testuser;
\c testdb testuser
You are now connected to database "testdb" as user "testuser".
select count(*) from information_schema.schemata
1
(1 row)
```

**Comment by jbeorse** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jeffisveryhungry@gmail.com
    Domain beorse.net has exceeded the max emails per hour (307/250 (122%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o8.sgmail.github.com ([167.89.101.199]:40413)
	by hp159.hostpapa.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-c877-jeff=beorse.net@sgmail.github.com>)
	id 1dgMDo-000f71-RT
	for jeff@beorse.net; Fri, 11 Aug 2017 22:32:16 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=q0VgpF/y8CuZz9Uu8XxTsaOOSMc=; b=ooDdWDg8sHY+cIUu
	jo2qZYqBiWr+veHMsWDBGFqb1AE69sbDeQD9qDWTso1zmh5BvRxmYsYjBTY+9oxv
	DVqYYIhbek5caKv2TMaJynENzOA6j6XXSULPWTh4boBP9TJ7CrTn3nFafj2L4VFv
	GsgINrAx7U5LcyY0imlctCasV10=
Received: by filter0941p1mdw1.sendgrid.net with SMTP id filter0941p1mdw1-27688-598E6889-19
        2017-08-12 02:31:37.233469507 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0005p1iad1.sendgrid.net (SG) with ESMTP id SoLjUkVLTT6UuoniaatZfQ
	for <Jeff@Beorse.net>; Sat, 12 Aug 2017 02:31:37.182 +0000 (UTC)
Date: Sat, 12 Aug 2017 02:31:37 +0000 (UTC)
