### ISSUE TITLE
Wiki Aggregate AWS Install: aggregate requires mySql 5.7 and Linux AMI only has 5.6

### ISSUE THREAD

**Issue by syldor** [opendatakit/opendatakit#1272]
When following the wiki Aggregate AWS install, the application cannot start because of a syntax error in the SQL. 
It's because the installed version of  `sudo yum install mysql mysql-server`  is 5.6.

  Installing 5.7 with `yum localinstall https://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm` doesnt-work neither because AMI doesn't have systemd.

  Thus it seems that aggregate should be installed on another distribution, like Ubuntu. Is that right ?

**Comment by mitchellsundt** [comment]
This document is contributed by the community and largely maintained by updates from the community, and hasn't been updated for 1.4.13. 

You likely need to use a newer operating system image (AMI). 

The instructions will differ rather significantly with different Linux distributions. I'd recommend remaining in the same distribution, just a newer OS level.

If you have updated instructions, please contribute them back (e.g., here), and I will update the documentation with those newer instructions.
