### ISSUE TITLE
Error Deploy ODKAggregate and SQL Server

### ISSUE THREAD

**Issue by eder-toledo** [opendatakit/opendatakit#1273]
Hi community 

I am configuring ODK Aggregate.

#### Software and hardware versions 
ODK Aggregate v1.4.13 windows-installer.exe W7 with SQL Server and Tomcat

#### Problem description

404 Not Found

I hope you can help me

I attach my settings

![jdbc driver](https://cloud.githubusercontent.com/assets/2104229/23971962/a30a2fb4-0995-11e7-8b89-d730494308ce.PNG)
![sqldb](https://cloud.githubusercontent.com/assets/2104229/23971967/a35e932e-0995-11e7-8c19-99145d98b6ca.PNG)
![sqldll](https://cloud.githubusercontent.com/assets/2104229/23971964/a32b8664-0995-11e7-91b1-d9e18d9da548.PNG)
![sqllibs in aggregate](https://cloud.githubusercontent.com/assets/2104229/23971963/a3263aec-0995-11e7-87a7-abbaf2a0f292.PNG)
![tomcat](https://cloud.githubusercontent.com/assets/2104229/23971965/a32bc4ee-0995-11e7-9af1-a1f6e80392bf.PNG)
![odkaggregate 404](https://cloud.githubusercontent.com/assets/2104229/23971968/a3a42984-0995-11e7-9fa8-27a987150dd3.PNG)
[Logs.txt](https://github.com/opendatakit/opendatakit/files/846060/Logs.txt)

**Comment by mitchellsundt** [comment]
Closing this issue. Please continue to use the opendatakit@ group for installation and usage questions.
