### ISSUE TITLE
ODK source code

### ISSUE THREAD

**Issue by Gerardatc** [opendatakit/opendatakit#1274]
Good morning,

How can I find the ODK source code?

Thanks

Gerard

**Comment by mitchellsundt** [comment]
Seriously?

How about clicking on the "developer wiki" link on this page: 
https://github.com/opendatakit/opendatakit

That takes you to here:
https://github.com/opendatakit/opendatakit/wiki

On which you have a nice table of project names and details. 

Click on the name of a project. Any project. It takes you to the source code.
