### ISSUE TITLE
Hello, I built a survey by XLSFORM. But I have problems finding a site to validate the online questionnaire and convert it to XML

### ISSUE THREAD

**Issue by aladjisy** [opendatakit/opendatakit#1275]
#### Software and hardware versions 
Aggregate v1.x.x, Survey vx.x.x, Android vx.x.x, device used...

#### Other information 
Things you tried, stack traces, related issues...

**Comment by yanokwa** [comment]
See http://opendatakit.org/xiframe/. https://opendatakit.org/use/xlsform/ and http://xlsform.org/#xlsform-tools also have alternatives.

**Comment by aladjisy** [comment]
Hello thanks to you for council. 
Now I need to submit questionnaire and convert in XML form. if I do it I receive this message "Error: There should be a choices sheet in this xlsform. Please ensure that the choices sheet name is all in small caps and has columns 'list name', 'name', and 'label' (or aliased column names).''
I don't arrive to detect this error signaled''

**Comment by yanokwa** [comment]
@aladjisy This isn't a feature request or bug, so I'd recommend you search the forum at http://groups.google.com/forum/#!forum/opendatakit for an answer. If you don't find it, post a question on that same forum.
