### ISSUE TITLE
Unable to drag or zoom map in ODK Aggregate visualization tool using mouse

### ISSUE THREAD

**Issue by ghost** [opendatakit/opendatakit#1281]
#### Software and hardware versions 
Aggregate v1.4.13 (probably all)

#### Problem description
I cannot drag or zoom the map in visualization tool in ODK Aggregate using mouse. Only zoom in and zoom out buttons in the lower right corner are working. The map is almost useless. 

#### Steps to reproduce the problem
1. On the Submissions tab choose a form, which contains column of location type and submissions.
1. Press Visualize button.
1. Choose type "Map".
1. Choose "Geopoint to Map".
1. Press "Map It" button.
1. Try to drag or move the map using mouse.

#### Expected behavior
It should be possible to drag or zoom the map using mouse.

**Comment by nodarik** [comment]
HI there

i can confirm that i have the same issue as skyf1sh

**Comment by shripatel** [comment]
Is it resolved ? i am also facing the same issue.

**Comment by lognaturel** [comment]
@ggalmazor Any chance this could be a quick win? It comes up fairly frequently -- https://forum.opendatakit.org/t/unable-to-drag-or-zoom-map-in-odk-aggregate-visualization-tool-using-mouse/6609/5

**Comment by ggalmazor** [comment]
I don't know.... I'll look into it :)

**Comment by ggalmazor** [comment]
It was super easy. I'm creating a PR for this :)
