### ISSUE TITLE
JSON Server Publisher uses Latin-1 Encoding, not UTF-8

### ISSUE THREAD

**Issue by taylordowns2000** [opendatakit/opendatakit#1283]
#### Software and hardware versions 
Aggregate v1.4.7 Production

#### Problem description
The ODK Aggregate JSON Publisher appears to use Latin-1 encoding, despite seeming to demand UTF-8. This causes failures at least when sending survey data containing the special character `é`.
```
65 72 5f 6e 61 6d 65 22 	e r _ n a m e " 
3a 22 54 e9 6c 6f 72 22 	: " T . l o r " 
7d 5d 7d                	} ] } 
```

#### Possible fix?
[String Entity toString doesn't have charset](https://github.com/opendatakit/aggregate/blob/7ebf4db6e3c123fb25662774545c822757e0d284/src/main/java/org/opendatakit/aggregate/externalservice/JsonServer.java#L194)
I'll submit a PR right now to show the proposed change, but I can't run this on my local machine yet.

#### Steps to reproduce the problem
1. Spin up Aggregate on Google AppSpot
2. Set up a form with an active JSON Alpha Publisher that sends data to a server which will give you access to the binary. I use https://ngrok.com/ so inspect the requests.
3. Submit data via ODK Collect which includes a special character. I've used "Télor" in this example.
4. Inspect the POST coming from Aggregate and note that the `é` is encoded as `e9` (binary in hex), rather than `c3 a9`. (Inspector image below.)
![image](https://cloud.githubusercontent.com/assets/8732845/26736057/86562c70-4792-11e7-8c53-965ed3f94c12.png)

Note that while it's less obvious, you can tell the difference using Requestb.in. In the image below you'll see that the second post (from ODK Aggregate) is Latin-1 encoded—we know this because it only contains 435 bytes, while the first post, made by me using UTF-8 encoding, is 436 bytes.
![image](https://cloud.githubusercontent.com/assets/8732845/26736205/1b84c478-4793-11e7-9f05-0c673174845d.png)

#### Expected behavior
Posts to JSON servers should use UTF-8 encoding.
```
45 6e 74 65 72 5f 6e 61 	E n t e r _ n a 
6d 65 22 3a 22 54 c3 a9 	m e " : " T . . 
6c 6f 72 22 7d 5d 7d    	l o r " } ] } 
```
#### Other information 
I'm wondering if this is an issue with ODK Aggregate, or with Tomcat. It seems that you can set the request headers, but I'm not a Java developer and haven't spun up ODK Aggregate on my machine.

These are what seem to be the relevant bits:
1. [Defining UTF8_ENCODE in HtmlConsts](https://github.com/opendatakit/aggregate/blob/master/src/main/java/org/opendatakit/common/web/constants/HtmlConsts.java#L147)
2. [Create submissionJsonObj](https://github.com/opendatakit/aggregate/blob/7ebf4db6e3c123fb25662774545c822757e0d284/src/main/java/org/opendatakit/aggregate/externalservice/JsonServer.java#L184)
3. [Send the post using HttpEntity](https://github.com/opendatakit/aggregate/blob/7ebf4db6e3c123fb25662774545c822757e0d284/src/main/java/org/opendatakit/aggregate/externalservice/JsonServer.java#L127)
4. [String Entity toString doesn't have charset—this might be the culprit](https://github.com/opendatakit/aggregate/blob/7ebf4db6e3c123fb25662774545c822757e0d284/src/main/java/org/opendatakit/aggregate/externalservice/JsonServer.java#L194)

@acawood777 thanks for bringing this to my attention
@rorymckinley thanks for digging in with me

**Comment by acawood777** [comment]
@taylordowns2000 Thanks for tracking the issue down!

This is currently problematic for us as we use the JSON publisher exclusively.
Every time we get a submission with one of these characters the JSON endpoint responds with something other than a 200, and the publisher then gets stuck on that submission, doing endless retries without progressing.

**Comment by jovaee** [comment]
It would seem that @taylordowns2000 does indeed work.

The text that was used:
![basic](https://user-images.githubusercontent.com/13763046/27487359-d1da094e-5833-11e7-9676-d9bfdd8895e5.PNG)

And the binary that was received for the text:
![bin](https://user-images.githubusercontent.com/13763046/27487386-e76efeae-5833-11e7-9bed-d548758479af.PNG)

The `é` is encoded as `c3 a9`

**Comment by taylordowns2000** [comment]
That's fantastic. Thanks for the test @jovaee . I'm closing this as @mitchellsundt has implemented the change in the `uimaster` branch of aggregate. Will reference this on that commit.
