### ISSUE TITLE
Supporting Ethiopian Calendar Widget For ODK

### ISSUE THREAD

**Issue by benimant** [opendatakit/opendatakit#1284]
can we add Ethiopian date widget for ODK..the full source code is developed by commcare and can be found at https://confluence.dimagi.com/display/commcarepublic/Alternate+Calendar+Formats+for+CommCare+Android...

this is not an issue but we can take it as a feature

**Comment by yanokwa** [comment]
Moving to https://github.com/opendatakit/collect/issues/1113

**Comment by lognaturel** [comment]
@benimant The Ethiopian calendar is now available in ODK Collect v1.11.0! 

For feature requests, https://forum.opendatakit.org/c/features is now the best place. See you on the forum! 😊

**Comment by benimant** [comment]
Thank You So Much The ODK Team..it means a lot for Ethiopian ODK Users

**Comment by lognaturel** [comment]
Yay! 🎉
