### ISSUE TITLE
Long URL in Rest Service throw and internal error

### ISSUE THREAD

**Issue by achajon** [opendatakit/opendatakit#1289]
#### Software and hardware versions 
From Web browser in setting page using chrome 

#### Problem description
I use Azure to import data using Rest Service JSON POST but the request URL is long about 250 character, and the setting page throw me an Internal error when I put long URLs.

#### Steps to reproduce the problem
Create a new Form -> go to Settings put into Rest Services section: service name: JSON POST then a long Service URL with more than 250 characters.

#### Expected behavior
in google chrome console throw an Internal error.

#### Other information 
With short URL works fine.

**Comment by linl33** [comment]
Could you clarify on the Rest Service JSON POST? Is this coming from an Open Data Kit tool?

**Comment by jbeorse** [comment]
We can't track this to any ODK tool. Closing
