### ISSUE TITLE
selects form is broken, select_one_with_other won't return the right value

### ISSUE THREAD

**Issue by nilesr** [opendatakit/opendatakit#1291]
#### Software and hardware versions 
Tables and survey development branch

#### Problem description
This is from the select formDef.json
```json
{
  "clause": "if",
  "condition": "selected(data('color'), 'teal')",
  "_row_num": 42
},
{
  "comments": "selected function with arguement not included in choices.",
  "type": "acknowledge",
  "name": "confirmTeal",
  "display": {
    "prompt": {
      "text": "Teal birds are very unique.  Please confirm that you saw a <span style=\"color:aqua;\">teal</span> bird."
    }
  },
  "hideInContents": true,
  "_row_num": 43
},
{
  "clause": "end if",
  "_row_num": 44
},
```
However no matter what you put in the box, lowercase, uppercase, etc.., the teal confirm prompt will never appear.

#### Steps to reproduce the problem
Add a new row to the `select` table using survey

#### Expected behavior
Asks me if I'm sure I really saw a teal bird

**Comment by mitchellsundt** [comment]
Looked into this. It does work, but the input field for "Other" is initialized to have a space. When the compare to "teal" is made, it doesn't trim spaces, and so the " teal" (not first deleting the space) that you would naively enter does not match "teal". The warning box should also have a required predicate so you can't navigate off the screen without acknowledging the presence of teal.

**Comment by nilesr** [comment]
Opened a different issue about the spaces
