### ISSUE TITLE
Need to document that if you don't put your assign in the model sheet, it won't do anything

### ISSUE THREAD

**Issue by nilesr** [opendatakit/opendatakit#1304]
#### Software and hardware versions 
survey 210c

#### Problem description
If you put an assign with a calculation and the name `some_column_id` in your xslx, that column id won't actually be created because xlsx converter doesn't know if your calculation is going to return a string, number, etc...., so you have to manually add a column with the exact same name in the model sheet or your assign won't do anything.

#### Steps to reproduce the problem
Use an assign without a model sheet

#### Expected behavior
Documentation, maybe an xlsx converter warning

**Comment by jbeorse** [comment]
Fixed or not an issue as of RC2 or earlier
