### ISSUE TITLE
ODK Tables does not run initialization task on clean install

### ISSUE THREAD

**Issue by mitchellsundt** [opendatakit/opendatakit#1306]
Something is broken. ODK Tables on a clean install does not detect and run the initialization task. It doesn't seem to pay attention to the initialization flags. I.e., Reset Configuration then open ODK Tables, and it will not invoke the intialization task.

You now MUST force close Tables, then open it in order for initialization to run. 
That isn't how it used to work.

**Comment by jbeorse** [comment]
Fixed or not an issue as of RC2 or earlier
