### ISSUE TITLE
ODK Tables webkit has hardware speed-up disabled

### ISSUE THREAD

**Issue by mitchellsundt** [opendatakit/opendatakit#1309]
This is present in the ODK Tables webview:

  setLayerType(View.LAYER_TYPE_SOFTWARE, null); 

This is a work-around that was added for the split-screen webkit to get around a timing issue that occurred on fast tablets with hardware acceleration -- where the view data for the list view returned data from the detail view -- this occurred about 50% of the time when you rotated the tablet causing a refresh. The issue was never verified as fixed (Mitch's website port demonstrated this same behavior 100% of the time).  Mitch can verify as fixed after a re-porting of the changes back to the website.

**Comment by jbeorse** [comment]
If we can resolve [issue 1312](https://github.com/opendatakit/opendatakit/issues/1312) then we should undo this change.

**Comment by nilesr** [comment]
I have fixed this
