### ISSUE TITLE
Datetime picker gives unexpected results

### ISSUE THREAD

**Issue by jbeorse** [opendatakit/opendatakit#1311]
#### Software and hardware versions 
Pre release of rev 210c

#### Problem description
Datetime Picker autofills itself with today's date in JS but records nothing if the user doesn't modify that value (never selects it). 

#### Steps to reproduce the problem
Load a survey with a datetime picker and press next without touching any of its elements.

#### Expected behavior
Datetime picker should always record what it displays to the database if the user hits next. Either it shouldn't initialize to today's date (rather initialize to blank) or it should record the default value without user interaction. My vote is it shouldn't initialize to today's date. 

#### Other information 
The code that initializes it to today's date is in this commit:
https://github.com/opendatakit/app-designer/commit/1ae0895f83b4aa851c6e32e21bda1fdb9b9c465d

**Comment by linl33** [comment]
Fixed
