### ISSUE TITLE
Increase collected images accessibility / Store media files into database and server file system

### ISSUE THREAD

**Issue by mathieubossaert** [opendatakit/opendatakit#1313]
Good evening,
It's so easy to collect images with Collect that it's a little bit frustrating not to be able easily access it once they are in Aggregate.
It would be a great enhancement if Aggragete could store medias files into the database and into the file system or if Aggregate could purpose a way to access stored files by unique url.

**Comment by nilesr** [comment]
Sync client has a way of pulling down all the instance files for all of your submissions down to a folder on your computer, so you can view them however you like. I haven't tried it though, and it might be ODK2 only

**Comment by kusaasira** [comment]
@mathieubossaert Was this resolved?

**Comment by mathieubossaert** [comment]
No because we run ODK 1 and I did not have time to take a look at the method... I'll do it in e few weeks.
Thanks a lot.

**Comment by kusaasira** [comment]
Okay then. Let me know when you attempt to.

You're welcome.

**Comment by mathieubossaert** [comment]
Thanks to @DamienFRAZZONI we are close to solve this in PostgreSQL.  This article help us to transform bytea field to "large object" and then take advantage of lo_export() function :

https://gbatumbya.wordpress.com/2011/06/15/create-a-large-object-lo-from-binary-data-bytea-on-server-side/

**Comment by mathieubossaert** [comment]
Here is an example.

Let's create the CAST as in the page discoverd by @DamienFRAZZONI  : 
https://gbatumbya.wordpress.com/2011/06/15/create-a-large-object-lo-from-binary-data-bytea-on-server-side/

```sql
create or replace function blob_write(lbytea bytea)
   returns oid
   volatile
   language plpgsql as
$f$
   declare
      loid oid;
      lfd integer;
      lsize integer;
begin
   if(lbytea is null) then
      return null;
   end if;
 
   loid := lo_create(0);
   lfd := lo_open(loid,131072);
   lsize := lowrite(lfd,lbytea);
   perform lo_close(lfd);
   return loid;
end;
$f$;
CREATE CAST (bytea AS oid) WITH FUNCTION blob_write(bytea) AS ASSIGNMENT;
```

PostgrSQL need the oid of the object so we can't use a view, so we add a column to the "..._BLB" table and a trigger to populate the lo column : 

```sql
ALTER TABLE odk."FORM_SAISIE_OBS_ORTHO_V1_1_PHOTO_BLB" ADD COLUMN lo oid;
UPDATE odk."FORM_SAISIE_OBS_ORTHO_V1_1_PHOTO_BLB" SET lo="VALUE"

SELECT lo_export("VALUE"::oid, '/home/my_repo/'|| to_char(blb."_LAST_UPDATE_DATE", 'YYYYMMDDHH24MISS') || '_' || "UNROOTED_FILE_PATH")
FROM odk."FORM_SAISIE_OBS_ORTHO_V1_1_PHOTO_BN" bn
JOIN odk."FORM_SAISIE_OBS_ORTHO_V1_1_PHOTO_REF" ref ON bn."_URI" = ref."_DOM_AURI" 
JOIN odk."FORM_SAISIE_OBS_ORTHO_V1_1_PHOTO_BLB" blb on blb."_URI" = ref."_SUB_AURI";
```
In fact we should populate the lo column, write the file on disk and then set to null the lo column.

It works great ! But in PostgreSQL.

**Comment by kusaasira** [comment]
Hey,

This is biased. It is only based on the postgresql side only. How about the MySQL side now?
