### ISSUE TITLE
Survey does not correctly remove no-longer-available forms after a sync

### ISSUE THREAD

**Issue by mitchellsundt** [opendatakit/opendatakit#1328]
push the tablesdemo files to a device and initialize the odk tools.

Then point ODK Sync to https://opendatakit-2.appspot.com

and sync. 

This only populates 5 tables and deletes the others. 

Unfortunately, the list of available forms within ODK Survey is not updated.

**Comment by mitchellsundt** [comment]
Keeping this open as a tracking issue. The fix resolves issues during sync, but did not resolve issues if users adb push changes or reset configuration to trigger a rescan and tables or forms have been removed. In that case, the entries of missing form ids will not be removed. This is impacted by changes for website, where most interactions with forms need to be done outside of the forms provider, and that provider should then be changed to be read-only.

**Comment by clarlars** [comment]
Thanks for keeping track of these issues.  The list of forms will be updated if directories are deleted, but empty directories are created unnecessarily.  I've opened issue https://github.com/opendatakit/opendatakit/issues/1335 to address this.  Also, created issue https://github.com/opendatakit/opendatakit/issues/1334 to capture your requested changes to the FormsProvider for tracking.  I'll close this issue now for clarity.
