### ISSUE TITLE
Services no longer supports gmail account using Aggregate 1.4.15

### ISSUE THREAD

**Issue by clarlars** [opendatakit/opendatakit#1329]
#### Software and hardware versions 
Android 5.1
Services rev 212a
Aggregate 1.4.15

#### Problem description
If you try to authenticate with a gmail account in Services rev 212a, you will get a toast message saying "Authentication Failed: android.accounts.AuthenticatorException: UNREGISTERED_ON_API_CONSOLE.

#### Steps to reproduce the problem
Using an Aggregate 1.4.15 instance and a gmail account on rev 212a, try to "Verify User Permissions" and you will consistently see the error described above.

#### Expected behavior
We should remove the option to use gmail accounts within Services.

**Comment by linl33** [comment]
Fixed by https://github.com/opendatakit/services/pull/57
