### ISSUE TITLE
Survey FormsProvider should be changed to read only

### ISSUE THREAD

**Issue by clarlars** [opendatakit/opendatakit#1334]
For the website most interactions with forms need to be done outside of the forms provider, and that provider should then be changed to be read-only as mentioned in https://github.com/opendatakit/opendatakit/issues/1328

**Comment by jbeorse** [comment]
Didn't Mitch fix this? Can we close it?

**Comment by wbrunette** [comment]
Apparently per @mitchellsundt the FormsProviders are now read-only
