### ISSUE TITLE
Update README and docs for sync-endpoint related containers

### ISSUE THREAD

**Issue by jbeorse** [opendatakit/opendatakit#1336]
#### Software and hardware versions 
N/A

#### Problem description
All 4 repositories with the sync-endpoint prefix could use a README refresh and possible documentation overview. For sync-endpoint-containers and sync-endpoint-default-setup this is probably pretty minimal, just adding our ODK header to the readme that links to the issue tracker and wiki, and bringing them in line with the other projects. For the other two this will be a bit larger of a task, and possibly involve a few other files (like README.txt in sync-endpoint)

**Comment by jbeorse** [comment]
Also, Jenkins tasks should be created and the typical branch structure should be added

**Comment by linl33** [comment]
Should we rename aggregate rest interface?

**Comment by jbeorse** [comment]
Yes, we should. I didn't do it in the interest of time before the release because it wasn't directly user facing. But IMO at least we should basically have no references to "Aggregate" in our released tools, they should all say "Cloud Endpoint" or some abbreviation thereof.

**Comment by linl33** [comment]
WIP: tracked here https://github.com/opendatakit/sync-endpoint/pull/5
