### ISSUE TITLE
ODK Survey save-and-exit does not save current changes

### ISSUE THREAD

**Issue by mitchellsundt** [opendatakit/opendatakit#1338]
This works in app-designer, but not in ODK Survey.

Open ExampleForm
Navigate to the select-multiple screen. 
Choose some items.
Click on "Example Form" button, and choose "Save Changes + Exit"

Now reopen the form, choose the instance you just saved (will be at the bottom of the list), and navigate to the select-multiple screen. Note that the items you checked were not saved.

In contrast, if you "Finalize Changes + Exit", the selections are saved.

In app-designer, both of these flows work.

The problem is that the stringifiedJSON that comes in on the saveAsComplete() and the saveAsIncomplete() calls is not respected and dropped. the finalization process does an add-checkpoint which records the values as the last checkpoint when finalize+exit is called, but the save+exit, which calls saveAsIncomplete(), does not first add a checkpoint, so the only record of the changes is in the stringifiedJSON, and since that gets dropped, no changes are applied.

**Comment by jbeorse** [comment]
Fixed or not an issue as of RC2 or earlier
