### ISSUE TITLE
grunt adbpush clear server config

### ISSUE THREAD

**Issue by orilevari** [opendatakit/opendatakit#1342]
When running grunt adbpush in app-designer, the server configuration gets reset to default, so I need to log back in to the server everytime I test a change during development. Is this intended?

**Comment by jbeorse** [comment]
The issue was that @orilevari didn't have the the app/output/props directory in his fork. This is necessary for the prop storage to work correctly.

**Comment by nilesr** [comment]
So git doesn't create empty directories by default when you're cloning. A potential solution would be to add an empty file to that folder

**Comment by jbeorse** [comment]
You committed that empty file already for that reason. It just got lost in the merge somehow. It was probably a mistake on my part merging to the shared fork. I think any fresh clone or careful merge should be fine
