### ISSUE TITLE
aws install wiki - clarification on ICMP

### ISSUE THREAD

**Issue by danbjoseph** [opendatakit/opendatakit#1359]
https://github.com/opendatakit/opendatakit/wiki/Aggregate-AWS-Install#details
has the following:
> To avoid potential problems with MTU settings and packet loss, also add a rule to allow "All ICMP". 

there are two ICMP options:
![screen shot 2017-11-14 at 11 58 54 am](https://user-images.githubusercontent.com/4806884/32793161-2d7718c6-c933-11e7-8220-b66f8da7581d.png)

should a rule be added for each?

**Comment by lognaturel** [comment]
👍 This brings up a higher-level question about what to do with the wiki. Should we perhaps move everything to docs.opendatakit.org so that they can more easily be community-maintained and kept centralized? The challenge with a GitHub wiki is that I am almost sure editing the wiki requires having code commit privileges. 

@ggalmazor @adammichaelwood @yanokwa

**Comment by danbjoseph** [comment]
I didn't even bother looking into editing the wiki 😶 
but if the docs were in a repo i would be happy to submit a pull request
and it would also let people use something like prose.io to edit, or just the GitHub web interface?

**Comment by lognaturel** [comment]
😊 Don't worry, GitHub's permissions being what they are I don't think it's a great solution anyway.

The repo would be https://github.com/opendatakit/docs. It uses restructured text and Sphinx and you could certainly edit with something like prose.io. Does it allow for committing to branches easily? The caveat is that it's ideal to build the docs locally and make sure they look as they should (instructions at http://docs.opendatakit.org/contributing/).

**Comment by lognaturel** [comment]
Perhaps http://docs.opendatakit.org/aggregate-install#installing-on-aws-cloud could be updated with all the info from the wiki and the wiki page could be retired.

**Comment by lognaturel** [comment]
(also I don't know the answer to this question or I would have given it to you)

**Comment by ggalmazor** [comment]
I see benefits and caveats on both approaches, but this matter seems to be valuable for people both developing and using Aggregate. Therefore, the wiki feels more appropriate. 

Maybe leaving the code repo for development and build stuff is the right thing to do but then we have to be careful and update the wiki whenever code changes affect the deployment.

**Comment by danbjoseph** [comment]
It's a little awkward that right now the same process is covered in 3 places:
- https://opendatakit.org/use/aggregate/#Installing_an_AWS_Instance
- http://docs.opendatakit.org/aggregate-install/#installing-on-aws-cloud
- https://github.com/opendatakit/opendatakit/wiki/Aggregate-AWS-Install

**Comment by lognaturel** [comment]
Awesome, I think we have 🎶consensus🎶.

I'm guessing that https://opendatakit.org/use/aggregate/#Installing_an_AWS_Instance was the source of http://docs.opendatakit.org/aggregate-install/#installing-on-aws-cloud. It looks like there are a couple of extra things at https://github.com/opendatakit/opendatakit/wiki/Aggregate-AWS-Install that should be transferred. Once it's verified that everything is in the docs version we can redirect the other two.

**Comment by lognaturel** [comment]
Filed at https://github.com/opendatakit/docs/issues/355

**Comment by yanokwa** [comment]
In my experience, the only inbound ports that are needed to get Aggregate to work are whatever ports you need for HTTP/HTTPS. I've never had ICMP enabled and never had a problem. But it seems like IMCP plays a nice to have role in IPv4 and a must have role in IPv6
- https://shouldiblockicmp.com
- https://security.stackexchange.com/questions/22711/is-it-a-bad-idea-for-a-firewall-to-block-icmp#comment36632_22713

So yeah, I would recommend allowing it for both.

**Comment by wbrunette** [comment]
fixed by https://github.com/opendatakit/docs/issues/355
