### ISSUE TITLE
aws install wiki - tomcat version listed not available on newest AMI

### ISSUE THREAD

**Issue by danbjoseph** [opendatakit/opendatakit#1360]
The current AMI version is: Amazon Linux AMI 2017.09.1 (HVM), SSD Volume Type - ami-32d8124a

The [2017.09 packages](https://aws.amazon.com/amazon-linux-ami/2017.09-packages/) include:
> tomcat-native-1.2.10
tomcat7-7.0.81
tomcat8-8.5.16

The [2017.03 packages](https://aws.amazon.com/amazon-linux-ami/2017.03-packages/) include:
> tomcat-native-1.2.10
tomcat6-6.0.53
tomcat7-7.0.77
tomcat8-8.0.43

Trying to run `sudo yum install tomcat6` (as noted in the wiki) on the newest AMI version will return:
```
No package tomcat6 available.
Error: Nothing to do
```

The [Aggregate Tomcat Install](http://opendatakit-dev.cs.washington.edu/1_0_tools/aggregate/tomcat_install) notes are for Tomcat 8. (So will try `sudo yum install tomcat8` for an AWS install.)

**Comment by lognaturel** [comment]
Closed by opendatakit/docs#354
