### ISSUE TITLE
Months in datetime combo picker are English only

### ISSUE THREAD

**Issue by jbeorse** [opendatakit/opendatakit#1363]
#### Software and hardware versions 
Survey rev218

#### Problem description
The month menu in the date time picker is not localizable like the rest of the text. Raised in this [forum post.](https://forum.opendatakit.org/t/getting-todays-date-and-different-formats-for-dates-in-odk-2-0/11212)

#### Expected behavior
The date time picker should show localized months. For a start it could show month numbers instead of English abbreviations.

**Comment by linl33** [comment]
Fixed by https://github.com/opendatakit/app-designer/pull/72
