### ISSUE TITLE
I want to display an image on start page of form..how to do it in xml form

### ISSUE THREAD

**Issue by umeshtiwari111** [opendatakit/opendatakit#1365]
#### Software and hardware versions 
Survey vx.x.x, Android vx.x.x, device used...

#### Other information 
Things you tried, stack traces, related issues...

**Comment by lognaturel** [comment]
Hi @umeshtiwari111! GitHub is for keeping track of software issues and tasks. For support, please use the forum - https://forum.opendatakit.org/. You should be able to find your answer by searching through old posts. If you’re using XLSForm also please make sure to review http://xlsform.org/
