### ISSUE TITLE
app-designer pushing to incorrect folder

### ISSUE THREAD

**Issue by MatthewKarami** [opendatakit/opendatakit#1367]
#### Software and hardware versions 
Android 7.1.1, Nexus 6p
Mac OS High Sierra 10.13.2
happens both with app-designer downloaded from website and cloned from github

#### Problem description
`grunt adb-push-default-app` creates a new config folder inside the config folder it should be pushing to, and pushes all data to the new folder.

#### Steps to reproduce the problem
1. delete opendatakit folder on phone
2. `grunt adb-push-default-app`
3. `grunt adb-push-default-app` again

the second push reliably creates the second folder, Although it seems that it sometimes happens on the first push.

#### Console snippit
`[ 53%] /sdcard/opendatakit/default/config/config/assets/csv/large_dataset.15000.csv: 27%`
`[ 54%] /sdcard/opendatakit/default/config/config/assets/csv/large_dataset.15000.csv: 28%`
`[ 54%] /sdcard/opendatakit/default/config/config/assets/csv/large_dataset.15000.csv: 29%`
`[ 54%] /sdcard/opendatakit/default/config/config/assets/csv/large_dataset.15000.csv: 30%`
`[ 54%] /sdcard/opendatakit/default/config/config/assets/csv/large_dataset.15000.csv: 32%`

(note the config/config)

**Comment by linl33** [comment]
Verified on Debian,
but `adbpush`, which calls `adbpush-default-app` internally, works

**Comment by wbrunette** [comment]
confirmed on windows as well
