### ISSUE TITLE
Alternate Survey form ordering

### ISSUE THREAD

**Issue by jbeorse** [opendatakit/opendatakit#1370]
Survey forms are currently only shown in alphabetical order by name. We should offer other display options, such as ordering by most recently updated (chronological) or grouping by tableID. I propose a menu item with a radio button that offers different display options.

**Comment by SatyamBansal** [comment]
@opendatakit-bot claim

**Comment by SatyamBansal** [comment]
@jbeorse Here is the implementation of sorting menu with radio buttons 

![screenshot_1519753942](https://user-images.githubusercontent.com/19202937/36745448-83e12de8-1c15-11e8-8e1f-41477732c6b0.png)
![screenshot_1519753948](https://user-images.githubusercontent.com/19202937/36745447-839cb28a-1c15-11e8-9459-bc36b632beb4.png)


sorting by tableid and name is working fine but m unable to sort chronologically , since it seems there  is currently no field available in forms table from which i can get last modified date , i tried with the column FormsColumns.Date but  indicates the last downloaded date of the form not the last used date.

**Comment by jbeorse** [comment]
@SatyamBansal This is looking great to me so far. I like the UI you have created.

I looked into your issues with dates. I tried filling out a form in Survey and finalizing it. To my surprise, the "Last Updated" date did not change. If I clicked the form name and looked at the instance list, I saw an accurate date on the individual instances. 

To me it looks like what is happening is "Last Updated" is read from the "date" column in the _formDefs table. I think this would only be updated if we updated or created a new formDef, and NOT when we add new instances. To me, this doesn't seem very useful, as this would be a fairly rare event. The "last updated" label, to me at least, implies the date of the most recent change to _any instance_ of the form. 

@wbrunette @clarlars @linl33 Is there any compelling reason to keep the "Last Updated" field defined this way? In my opinion we should change the wording to "Last Instance Update" and use it as described above. This would involve querying the table with id **tableId** where column **_form_id** matches the **formId** and  finding the max of the **savepoint_timestamp** column. This might create a bit of a performance hit when rendering the homepage when you have a lot of forms. If that's the case, maybe we can remove the label altogether, and only perform these queries if the user explicitly chooses to order forms chronologically? 

@SatyamBansal while we sort this out, go ahead and remove the "Date modified" option from the drop down and just submit a pull request with the "Table ID" and "Name" options. Regardless of the direction we go, the chronological option is going to be more complicated and we can get it in a future pull request.

**Comment by jbeorse** [comment]
By the way @SatyamBansal you can explore the database by pulling it from the device and browsing it with a SQLite browsing tool. The database is located in the _opendatakit_ folder under _opendatakit/default/data/webDb_. You can pull it to your PC with the command:
`adb pull /sdcard/opendatakit/default/data/webDb .`

After you have pulled it you can view it with a browser. I use this one: https://github.com/sqlitebrowser/sqlitebrowser
From there you can explore the full database structure and run test queries. You can add or modify instances in Survey and Tables and then pull the database again and see how it changes the tables. This can be useful for debugging.

**Comment by wbrunette** [comment]
@SatyamBansal we will hopefully have an answer for you tomorrow. I am doing an indepth dive to make sure we understand the implications of these changes.

**Comment by wbrunette** [comment]
We found one issue where date is being used and could effect the logic. We should consider if there is a way to get similar behavior without using the "Last Updated" field.

https://github.com/opendatakit/survey/blob/master/survey_app/src/main/java/org/opendatakit/survey/activities/MainMenuActivity.java##L585

**Comment by SatyamBansal** [comment]
I see its used to initialise trackingFormLastModifiedDate variable , but i tried finding where this variable is used , but cant find it apart from it being initialised  . Am i missing something?

**Comment by wbrunette** [comment]
On line 585, it appears to set the value of the boolean changed, then on 593 it will cause the frameworkBaseUrl to be different, causing other things downstream to be different. Understanding the effects downstream is the next step.

**Comment by jbeorse** [comment]
Address in PR https://github.com/opendatakit/survey/pull/42
