### ISSUE TITLE
Configure Services's Server Setting with a Barcode

### ISSUE THREAD

**Issue by wbrunette** [opendatakit/opendatakit#1373]
Organizations want to be able to rapidly configure devices and not constantly type in the settings for server setup. The 3 basic pieces of information needed are
1) URL
2) Username (or anonymous)
3) Password

Services should be modified to add in a button that launches a barcode scanner that reads a 3D barcode.
This 3D barcode could contain all, none, or a subset of the 3 pieces of information. The information from the 3D barcode should be used to populate the 3 pieces of information in Services's server settings.

**Comment by laddha-adi** [comment]
@opendatakit-bot claim

**Comment by laddha-adi** [comment]
@wbrunette Hi, I have almost implemented this feature.
Was wondering what format should we use for QR Code? Should we use json or comma separated string?

**Comment by wbrunette** [comment]
@laddha-adi great question. My preference would be for a JSON object. I would proceed with JSON. If you are available you could join the ODK 2 developer call and solicit further feedback from people about formatting and anything else: https://forum.opendatakit.org/t/odk-2-0-developer-call-2018-03-13/12137?u=w_brunette

**Comment by laddha-adi** [comment]
@wbrunette  Will surely be joining the developer call. I too think we should go with JSON.
Can you please review [this](https://github.com/opendatakit/survey/pull/43) so that I can send a pull request for this issue.

**Comment by laddha-adi** [comment]
@opendatakit-bot claim

**Comment by laddha-adi** [comment]
@opendatakit-bot claim
