### ISSUE TITLE
Increase text size of "Select the form to open"

### ISSUE THREAD

**Issue by jbeorse** [opendatakit/opendatakit#1374]
The header text for the form list in ODK Survey "Select the form to open" is quite small and hard to notice. This should be made more prominent for clarity.

**Comment by ptoles01** [comment]
As is the case elsewhere on this project, I'd like to take on this enhancement, but not sure of my next steps. I tried cloning the code but no luck. Please advise. This is my 1st attempt at a contribution, so I'm admittedly a bit green. -Thanks!

**Comment by ptoles01** [comment]
I use my browser to navigate to the gitHub repo for this project. From there, I choose the clone or download button on the right-hand side. A dialog box appears for me to navigate to the project directory on my PC. Once the project is downloaded to my chosen directory, I launch Android studio and navigate to the app directory of the project. Android Studio takes over from there by completing the project tree and such. Thus, I am not using the terminal OR Android Studio for the cloning. I am using GitHub directly.

**Comment by SatyamBansal** [comment]
I think u r clong this repository, this is only used as issue tracker.
There is seperate repository for each of the apps like opendatakit/survey,
for survey app and so on

**Comment by SatyamBansal** [comment]
May i work on this ?

**Comment by jbeorse** [comment]
@ptoles01 it looks like you're working on #1375, if so, it seems fine to have @SatyamBansal work on this. Can you confirm what you are working on? 

Regardless, it is a good exercise in learning the code base to make this change, even if only one of you ends up merging. Don't be afraid to go ahead and do it and submit a pull request.

**Comment by laddha-adi** [comment]
@opendatakit-bot claim

**Comment by laddha-adi** [comment]
The header text for the form list in ODK Survey "Select the form to open" was quite small and hard to notice. I have increased its text size from 14 sp to 21 sp.
closes #1374

**Comment by laddha-adi** [comment]
Resolved with opendatakit/survey#44
