### ISSUE TITLE
No Splash Screen is shown

### ISSUE THREAD

**Issue by codedsun** [opendatakit/opendatakit#1386]
#### Software and hardware versions 
Services, Android 6.0

#### Problem description
No splash screen is shown on opening of the app even after setting the checkbox preference to true.

#### Steps to reproduce the problem
1.  Launch the app.
2. Go to Toolbar and then navigate to settings
3. Under Device settings, check the 'Show Splash Screen' Checkbox to true.

#### Expected behavior
It should show the splash screen on the start of the app.

#### Other information 
The logcat doesn't shows anything noticeable about the Splash Screen.

**Comment by codedsun** [comment]
@jbeorse Please check the issue and I can send the PR asap.!

**Comment by wbrunette** [comment]
@codedsun thanks for pointing this out, but we do not have a splash screen on purpose. ODK Services is meant to be a background app and have Survey and Tables use it's functionality via intents without the user realizing they are changing apps. A splash screen launching would slow things down as you move between apps. Thanks for looking for bugs in ODK2 we appreciate your efforts!
