### ISSUE TITLE
Problem downloading instances

### ISSUE THREAD

**Issue by wendyomeara** [opendatakit/opendatakit#1399]
#### Software and hardware versions 
My ODK version is V12.2. I am using a Samsung Tab 3

#### Problem description
I use a USB connection to transfer files from my Android tablet to my laptop. 
I copy the entire 'ODK' folder onto my laptop.
Within the ODK folder, there are four subfolders: Forms/Instances/Layers/Metadata
I open Instances - subfolders are named by Form, in each of these, have xml individual forms. 
**In several cases, the xml file name (automatically generated) doesn't match the data inside. The data is overwritten by data from another instance. When I check this form on the tablet, the data appears correctly but each time the wrong data appears in this xml file when I transfer it to the computer.** 
For example, an instance with the title: Monthly Ind V16_2018-04-06_11-12-09 has data from participant X but should have data from participant Y. The data that appears is actually from another instance that has data from participant X titled: Monthly Ind V16_2018-04-12_10-42-46. So participant X's data appears twice. When you look at the instances on the tablet, data for participant X and Y appear correctly in their respective instances. 

It does not happen consistently on a specific tablet and only happens with about 5% of forms. This just started recently. 

#### Steps to reproduce the problem
I cannot predict when this will happen or reproduce it on purpose. It happens on about 2% of instances each time I download a batch of data to the tablet. 

#### Other information 
Things you tried, stack traces, related issues...

**Comment by wbrunette** [comment]
@wendyomeara thanks for filing a bug report. I am not familiar with version 12.2. One possibility is you might be using  ODK Collect version 1.2.2 or maybe ODK Collect version 1.12.2? The current version is 1.15.0. Do you see the same behavior when using the current device?

One problem with Android is the USB connection uses the MTP protocol which does not always fully update the files it is presenting when you plugin in a USB connection. It is a known problem that is tracked by this Android issue: https://issuetracker.google.com/issues/37071807
People have found if they reboot the device the MTP protocol used by USB will have a full refresh of the files via MTP. 

Additionally you might want to file this issue on Collect directly if the reboot does not seem to get the consistency you want or if there is a bug with ODK Collect. Collect's issue queue is available here: https://github.com/opendatakit/collect/issues

**Comment by yanokwa** [comment]
Closing because of no response. 

@wendyomeara if this is still a problem, please file it at https://forum.opendatakit.org/c/support.
