### ISSUE TITLE
Get data from a nodejs server

### ISSUE THREAD

**Issue by MorganDbs** [opendatakit/opendatakit#1401]
#### Problem description
Hi, is there a way I get data from an aggregate server using http request in my nodeJs server ? I need to get all the data and put it in pouchDb.

Have a good day

**Comment by wbrunette** [comment]
This is more of a question than an issue. I suggest asking your question on our forum (https://forum.opendatakit.org/) or asking in the developer slack channels (opendatakit.slack.com).

If you do not get a satisfactory answer in the forum then please file a feature request on the forum or on Aggregate's GitHub issue queue: https://github.com/opendatakit/aggregate/issues
