### ISSUE TITLE
grunt adbpush fails on Android 8 devices

### ISSUE THREAD

**Issue by clarlars** [opendatakit/opendatakit#1405]
#### Software and hardware versions 
Pixel C with Android 8.1.0 using ODK 2.0.5

#### Problem description
Running grunt adpbush fails on this device with the following error:

Running "exec:adbshell:run-as org.opendatakit.services rm -rf /data/data/org.opendatakit.services/app_default" (exec) task
>> run-as: package not debuggable: org.opendatakit.services
>> Exited with code: 1.
Warning: Task "exec:adbshell:run-as org.opendatakit.services rm -rf /data/data/org.opendatakit.services/app_default" failed. Use --force to continue.

#### Steps to reproduce the problem
Run "grunt adbpush" on a device running Android 8.1 with the official ODK 2.0.5 released binaries.

#### Expected behavior
"grunt adbpush" when using the released ODK 2.0.5 binaries should not fail.

**Comment by nilesr** [comment]
Oops, looks like [I wrote this line](https://github.com/opendatakit/app-designer/commit/d1409e853).

Hard to figure out what I was trying to do from the commit title, but I think I remember Jeff mentioning that his server settings were not being wiped when he did a clean + re-push of an app, and I was trying to fix that by removing the Services data folder

**Comment by karimbernardet** [comment]
Hi
I have the same error 
How to fix it please ?
Thanks
Karim

**Comment by wbrunette** [comment]
This will be fixed in version 2.1.0
