### ISSUE TITLE
Creating a user id with multiple value

### ISSUE THREAD

**Issue by mahbub977** [opendatakit/opendatakit#1413]
Is it possible to generate an unique id with multiple field.e.g: first two field fixed with some value, next two values for tab code (how to take tab code on login?), next two values for year,next two values for month, next 4 field filled up by data collector...
example id: RS031901SD13
Please help with some suggestion. 

Thanks

**Comment by yanokwa** [comment]
Support questions should go to https://forum.opendatakit.org/c/support
