### ISSUE TITLE
Fetching form definition resolving against briefcase form definitions Error parsing form definition: org.opendatakit.aggregate.exception.ODKIncompleteSubmissionData: Javarosa failed to construct a FormDef. Is this an XForm definition?

### ISSUE THREAD

**Issue by Rutayuga** [opendatakit/opendatakit#1415]
I cannot pull form from Server with below error, any assistance will be appreciated
Fetching form definition
resolving against briefcase form definitions
Error parsing form definition: org.opendatakit.aggregate.exception.ODKIncompleteSubmissionData: Javarosa failed to construct a FormDef. Is this an XForm definition?

#### Software and hardware versions 
Survey vx.x.x, Android vx.x.x, device used...

#### Other information 
Things you tried, stack traces, related issues...

**Comment by yanokwa** [comment]
Support questions should go on https://forum.opendatakit.org/c/support
