### ISSUE TITLE
odk collect upload behind a proxy server

### ISSUE THREAD

**Issue by mitchellsundt** [opendatakit/opendatakit#17]
*Migrated to opendatakit/collect#21 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

Originally reported on Google Code with ID 16
```
Can we get ODK Collect to work in WiFi connections where a proxy server is 
present? I noticed that the presence of a proxy server prevents the app from 
uploading the file/form. 
```

Reported by `yanokwa` on 2010-04-29 22:11:00

**Comment by hrrpnepal** [comment]
i had my own local server with some space. how can i setup ODK in my server so that i can run in my local server/

**Comment by lognaturel** [comment]
Hi @hrrpnepal! This is a closed issue. Can you please post your support request to https://forum.opendatakit.org/c/support. Please be sure to fill out the template completely and be as specific as you can about your configuration, server versions, etc.
