### ISSUE TITLE
Add support for answers given as a range

### ISSUE THREAD

**Issue by mitchellsundt** [opendatakit/opendatakit#187]
Originally reported on Google Code with ID 186
```
Enhancement.

Many answers we get are given as a range: 1-2 weeks, 3-4 days, etc.  Is there some
way that a type of answer can be a range (I'm thinking two sliders of numbers, like
the ones used for dates?)
```

Reported by `Emily.Kumpel` on 2011-02-17 17:50:51

**Comment by jnordling** [comment]
I like this idea, would this be a select_multiple with an appearance option for "range". humm or would that make sense, because when it is stored as a select_multiple which may not make sense due to the way aggregate stores select_multiple. Which data type are you thinking for this?
