### ISSUE TITLE
Add fingerprint scanning support

### ISSUE THREAD

**Issue by mitchellsundt** [opendatakit/opendatakit#497]
Originally reported on Google Code with ID 496
```
For Android OS (ARM based), we have the driver and ScanAPI for the Futronic FS80 to
capture a fingerprint image, but it has the following requirement:
 1. Have an USB Host port
 2. Have usbfs support in the kernel
 3. Have the root access right
 4. Have a folder "/data/" that can be read/write access.
 
Attached please find the libusb and ScanAPI libraries for Android, and the console
demo program with source code. To test it, you need to copy the libraries to the system
lib folder, then open the terminal, run as root user:
    #./ftrScanAPI_Ex_fs.
```

Reported by `yanokwa` on 2012-01-10 01:08:55

<hr>
 * *Attachment: [30_12_2010_scanapi_android_flock_bin_src.rar](https://storage.googleapis.com/google-code-attachments/opendatakit/issue-496/comment-0/30_12_2010_scanapi_android_flock_bin_src.rar)*

**Comment by antoniocvaraujo1** [comment]
> _Migrated to [opendatakit/collect#57 (comment)](https://github.com/opendatakit/collect/issues/57#issuecomment-244786167) by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)_
> 
> ```
> Bluetooth scanner: http://www.innovatescan.com/hardware/bluefin/
> Authentec SDK: http://forum.xda-developers.com/showthread.php?t=1206033
> ```
> Reported by `yanokwa` on 2012-01-17 16:03:17

Hi mitchellsundt. i got a futronic fs88h and i need to develop an android activty that reads the fingerprint and send it to webapi c#. Can you help ?
