### ISSUE TITLE
Request new feature - edit/update the data after uploaded

### ISSUE THREAD

**Issue by mitchellsundt** [opendatakit/opendatakit#628]
Originally reported on Google Code with ID 627

```
Hi there,

Can we edit/update the data after it is uploaded to google cloud? Please see the attached
file of what PoiMapper can do with editing. Thanks.

Best regards,
Chan Choth
```

Reported by `chanchoth` on 2012-07-09 06:44:53

<hr>
- _Attachment: 2012-06-22 07.49.05.png<br>![2012-06-22 07.49.05.png](https://storage.googleapis.com/google-code-attachments/opendatakit/issue-627/comment-0/2012-06-22 07.49.05.png)_

**Comment by jbeorse** [comment]
This functionality is included in the current 2.0 codebase
