### ISSUE TITLE
ODK Authentication stops working on ODK Collect for no apparent reason.

### ISSUE THREAD

**Issue by mitchellsundt** [opendatakit/opendatakit#693]
*Migrated to opendatakit/collect#82 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

Originally reported on Google Code with ID 692
```
We are running ODK Aggregate (v1.2.0) on our own server and it all seems to work fine.
We have set up ODK authenticated Data Collector users in Aggregate and matched those
credentials as stored username/password settings on the ODK Collect (v1.2.1) app on
our Android devices. Doing a "Get Blank Form" works fine with those credentials and
we get the form uploaded onto the Android device. "Fill Blank Form" works fine and
we can finish and finalize forms with no problems.

However, when it comes time to "Send Finalized Form", the Android phone reports an
authentication error (despite the credentials being correct) against the Aggregate
server and asks for a username and password to be entered. I can type in any valid
username and password and it still will not send the form. All sets of credentials
are in fact valid and work fine when we use a web browser to log in to Aggregate itself.

The only way we seem to be able to fix it is to do another "Get Blank Form" and re-upload
the same form. Magically the "Send Finalized Form" starts working again with no change
to the stored username/password settings.

Can anyone think of a reason why this might occur? (..and how we might stop it happening?)

Thanks

Evan Yates
```

Reported by `wbrunette` on 2012-09-26 18:13:03

**Comment by yismaw** [comment]
am using ODK data collect for field data collection the main problem is that sending a form to the surver ;when I tried to send it is impossible it says connection time out almost two weeks count even if I try in a high Internet connection is there any solution please help me.
    Thank you.

**Comment by benimant** [comment]
The problem might be on the Google App Engine..Did u pay ?..check that

**Comment by yismaw** [comment]
unable to pay don't u have any free assistance please!

**Comment by benimant** [comment]
the payment is not for me..its for Google App Engine..The app engine has  a
free quota for test purpose..but when ur data exceeds that limit u have to
pay for Google...Unless u cant send data to ODK aggregate..

If u need more assistant write me..benimant@gmail.com
