### ISSUE TITLE
Instance nodes should not start with numbers

### ISSUE THREAD

**Issue by mitchellsundt** [opendatakit/opendatakit#817]
Originally reported on Google Code with ID 816

```
A form with a <2013crop/> instance node will not validate. Change to <crop2013/> and
it validates. Instance nodes should not start with numbers. 
```

Reported by `yanokwa@nafundi.com` on 2013-04-26 13:59:42

**Comment by yanokwa** [comment]
Closing in favor of https://github.com/XLSForm/pyxform/issues/130. Build doesn't have this problem.
